// सरकारी कागदपत्रे व पुरावे — edited via admin.html "सरकारी कागदपत्रे" tab.
// summary text is ADMIN-REVIEWED. extractedText (OCR) is used for search only.
const EVIDENCE_DOCS = [
  {
    "id": "ev-1787383568850",
    "title": "RTI 12-8-26 (C.Gov)",
    "category": "Railway / Government Letters",
    "date": "12.08.2026",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "केंद्रीय रेल्वेच्या मुख्य प्रशासकीय अधिकाऱ्यांनी (बांधकाम) दिलेलं RTI उत्तर. यात नमूद आहे: हातकणंगले–इचलकरंजी नवीन रेल्वे मार्ग (8 किमी) 2017-18 च्या Pink Book मध्ये समाविष्ट होता. या प्रकल्पाचा Detailed Project Report (DPR) रेल्वे बोर्डाकडे 02.01.2020 रोजी सादर करण्यात आला — खर्च ₹180.73 कोटी व ROR (-12.73%). प्रकल्प अद्याप रेल्वे बोर्डाच्या तपासणीत (scrutiny) असून मंजूर झालेला नाही, त्यामुळे पुढील तपशील अद्याप शेअर करता येत नाहीत असं उत्तरात नमूद आहे.",
    "extractedText": "--- पान 1 ---\n—\nCENTRALRAILWAY\n« IND;\n$F ao Sy Office of the\n(4 ERIE Chief Administrative Officer (Const.)\nSe. 6\" floor, New Administrative Building\nSi il D.N. Road, CSMT, Mumbai-400 001\nNo. EW/106/RT1/2026/0L-295 Date: - 12.08.2026\nShri Vicky Manisha Balu Lokare\nSub: Information required under Section 6(1) of the RTI Act 2005.\nRef: Online RTI application No. CRAIL/R/T/26/00731 dated 22.07.2026.\nhocks\nर With reference to the above, the information available in Central Railway Construction\nOrganization for Hatkanangale -Ichalkaranji Railway project is given as under: -\nInformation Sought\n\n1 Please provide the certified copies of the | The work of Hatkanangale -\nofficial file notings and processing history of | Ichalkaranji new Railway line (8Km)\nthe Detailed Project Report (DPR) for the | appeared in the Pink Book of 2017-18.\nHatkanangale-Ichalkaranji New BG line which | The Detailed Project Report (DPR) of\nwas submitted to the Railway Board by the | the said project was submitted to the\nCentral Railway Construction Wing in the year | Railway Board on 02.01.2020, ata cost\n2018. प of Rs. 180.73 crore & ROR (-12.73%).\n\nThe same is under scrutiny of Railway\nBoard.\n\nProject is not sanctioned yet, hence\ndetails cannot be shared.\n\n2 As per the official Twitter announcement by | Under the RTI Act, public authorities\nCentral Railway dated 11 June 2017 the | are not obligated to answer questions\nfoundation stone for the Final Location Survey | that seek explanations, reasons,\nof this line was laid by the then Minister of | opinions, or justifications for actions\nRailways. Please state the specific technical or | or decisions. The Act focuses on\nfinancial reasons why the Railway Board has | providing access to information in the\nnot granted final sanction to this project even | form of records, documents, etc,\nafter 8 years. rather than interpretations or\n\nopinions.\nPlease provide copies of any correspondence | Project is not sanctioned yet, hence\nor official remarks exchanged between the | details cannot be shared.\nRailway Board and NITI Aayog or the Ministry\nof Finance regarding the fund allocation. for\nthis specific Hatkanangale-Ichalkaranji rail\nlink.\n\n4 Please intimate whether this project is | The work of Hatkanangale-\ncurrently under consideration for inclusion in | Ichalkaranji new Railway line (8Km)\nthe upcoming Pink Book or Budgetary | appeared in the Pink Book 0f2017-18.\nAllocation. What is the current official status of | The Detailed Project Report (DPR) of\nthis project file in the Railway Board? the said project was submitted to the\n\nRailway Board on 02.01.2020, ata cost\nof Rs. 180.73 crore & ROR (-12.73%).\nThe same is under scrutiny of Railway\nBoard.\n(scanned with OKEN Scanner\n\n--- पान 2 ---\nPeriod to which information relates: June 2017 | The work of ) Hatkanangale-\nto May 2026. Ichalkaranji new Railway line (8Km)\nappeared in the Pink Book of 2017-18.\nThe Detailed Project Report (DPR) of\nthe said project was submitted to the\nRailway Board on 02.01.2020, ata cost\nof Rs. 180.73 crore & ROR (-12.73%).\nThe same is under scrutiny of Railway\nBoard.\nFormat of Information: Certified Copies via | Project is not sanctioned yet, hence\nRegistered Post or Online RTI Portal. | details cannot be shared.\nThis is for your information please.\nIf you are not satisfied with this information, appeal to the above lies with the 1st Appellate\nAuthority, within 30 days, from the date of receipt of this communication.\nThe name and address of the First appellate Authority are given Below: -\nChief Engineer (Construction) South,\nFirst Appellate Authority,\nCAO (C)’s Office, NAB Bldg.,\n6th Floor, D.N. Road,\nCST Mumbai-400 001.\n3 5\noii\nDy.\\CE(C)PLG & CPIO\nRly. No. - 022674-54310\nEmail- dycecpl@gmail.com\n(scanned with OKEN Scanner",
    "originalFile": "evidence-1787383566049-rti-12-8-26-c.gov-.pdf",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-22T07:26:08.850Z",
    "updatedAt": "2026-08-22T07:26:08.850Z"
  },
  {
    "id": "ev-1956-loksabha",
    "title": "लोकसभा संदर्भ — 19 डिसेंबर 1956",
    "category": "Railway / Government Letters",
    "date": "19.12.1956",
    "authority": "लोकसभा (Lok Sabha), भारत सरकार",
    "referenceNumber": "",
    "tags": [
      "1956",
      "Lok Sabha",
      "Parliament",
      "Historical",
      "Earliest Record"
    ],
    "summary": "सध्या उपलब्ध असलेला सर्वात जुना पडताळलेला संसदीय संदर्भ — इचलकरंजी भागाच्या रेल्वे कनेक्टिव्हिटीसंदर्भात 19 डिसेंबर 1956 रोजीच्या लोकसभा कामकाजातील नोंद (पान 53-54). हा दस्तऐवज ऐतिहासिक संदर्भासाठी जतन केला आहे — तपशीलवार मजकुरासाठी मूळ PDF पहा.",
    "extractedText": "",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "originalFile": "evidence-1956-lok-sabha-reference.pdf",
    "createdAt": "2026-08-22T13:07:48.131Z",
    "updatedAt": "2026-08-22T13:07:48.144Z"
  },
  {
    "id": "ev-1787555731411",
    "title": "RTI 13-7-26 (C.Gov)",
    "category": "Railway / Government Letters",
    "date": "13.07.2026",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nग CENTRALRAILWAY\npe’. o Office of the\n(4 Sow Chief Administrative Officer (Const.)\nEERE) § 6५ floor, New Administrative Building\nBPE D.N. Road, CSMT, Mumbai-400 001\nNo. EW/106/RT1/2026/0L-274 Date: -13.07.2026\nShri Vicky\n3 Sub: Information required under Section 6(1) of the RTI Act 2005.\nRef: Online RTI application No. CRAIL/R/E/26/01707 dated 03.07.2026.\nकवन\nWith reference to the above, the information available in Central Railway Construction\nOrganization are given as under: -\n\nNo\n\n1 DPR Executive Summary: Please provide a | Project has not been sanctioned yet; hence details\ncertified copy of the Executive Summary and | cannot be shared.\n\nTraffic Survey findings of the updated Detailed\nProject Report (DPR) submitted to the Railway\nBoard.\n\n2 Pink Book Status: Please provide the current | The work of Hatkanangale- Ichalkaranji new Railway\nofficial status of the project listed under Pink | line (8Km) appeared in the Pink Book of 2017-18. The\nBook Item Number 12 (Central Railway New | Detailed Project Report (DPR) of the said project was\nLines). Provide copies of official | submitted to the Railway Board on 02.01.2020, at a cost\ncorrespondence regarding its clearance or | Of Rs. 180.73 crore & ROR (-12.73%). The same is under\npending queries. scrutiny of Railway Board.\n\ncopies of official correspondence regarding its clearance\nor pending queries are not available in this office.\n\n3 Financial and ROR Reconsideration: Please | copies of any official reviews or notes where this project\nprovide copies of any official reviews or notes | is being evaluated under the PM GatiShakti National\nwhere this project is being evaluated under the | Master Plan guidelines, bypassing the negative Rate of\nPM GatiShakti National Master Plan guidelines, | Return (ROR) of -12.73 percent, are not available in this\nbypassing the negative Rate of Return (ROR) of | office.\n\n-12.73 percent.\n\n4 Cost Sharing Infrastructure: Please provide | There is no cost sharing between the Government of\ncopies of letters or proposals sent to or | Maharashtra and the Indian Railways for this project.\nreceived from the Government of Maharashtra\nregarding 50:50 cost-sharing or land allocation\nfor this 8 KM line.\n\n5 Land Acquisition Plans: Please provide copies | Project has not been sanctioned yet, hence details\nof the preliminary alignment reports or joint | cannot be shared.\nmeasurement surveys identifying affected\nareas in villages between Hatkanangale and\nIchalkaranji.\n\nThis is for your information please.\n\nIf you are not satisfied with this information, appeal to the above lies with the 1st Appellate Authority,\n\nwithin 30 days, from the date of receipt of this communication.\n\nThe name and address of the First appellate Authority are given Below: -\n\nChief Engineer (Construction) South,\n\nFirst Appellate Authority,\n\nCAO (C)'s Office, NAB Bldg,\n\n6० Floor, D.N, Road,\n\nCST Mumbal-400 001. 0\n\nOND\nonly Bada\nDy. CE(C)PL & CPIO\nRly. No. - 022674-54310\nEmail- dycecpl@gmail.com\n(scanned with OKEN Scanner",
    "originalFile": "evidence-1787555728745-rti-13-7-26-c.gov-.pdf",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-24T07:15:31.411Z",
    "updatedAt": "2026-08-24T07:15:31.411Z"
  },
  {
    "id": "ev-1787555970059",
    "title": "RTI 19-5-26 (C.Gov)",
    "category": "RTI",
    "date": "15-05-2026",
    "authority": "",
    "referenceNumber": "DRMOP/R/P/24/00164",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nI  ,;  iNoi 4 '  ~- .. . ~'.  . .   . .. .   . . .   .  CENTRAL   RAILWAY  • • •   I E. • er (Co-ord) & Chief Public Information Officer Office of the  Sr.  D1v1s1ona ng1ne (Engg), .   . • • •   I   R ·1 ay ORM Office   Building, near Pune Railway Station, Pune D1v1s1on, Centr~un!'  ~  411   001 Tel.No.020-26105312 Central Railway No. PA.W.RTI/2026 Dy. CE /Construction, Satara ORM (W) Pune Pune Division Date: 15-05-2026 Sub: Transfer of RTI cases   under   provision of section-6 (3) of RTI Act- Case of Shri.Vicky Balu Lokare Ref: 1. Online RTI Registration   No.DRMOP/R/P/24/00164   dated   14.05 .2026. Please   find enclosed herewith an online RTI   application of Shri.   Vicky   Balu Lokare received in this office. Since   the   information   sought   therein   is   pertaining   to   Dy CE Construction, Satara.   Hence, this RTI is   transferred   herewith   in   accordance   with Section -6   (3) of RTI   Act, 2005. It is, therefore requested   to   communicate   the   information   directly   to   the RTI applicant under advice   to   this office.  Uk,~o~~  DRM(Wks)Pune",
    "originalFile": "evidence-1787555967577-rti-19-5-26-c.gov-.pdf",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-24T07:19:30.059Z",
    "updatedAt": "2026-08-24T07:19:30.059Z"
  },
  {
    "id": "ev-1787556192164",
    "title": "RTI 02-4-26 (C.Gov)",
    "category": "Photos / Scanned Documents",
    "date": "",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nCENTRAL   RAILWAY  . • •   l Engine·er (Co-ord) & Chief Public Information Officer Office   of the Sr. D1v1s1ona ) (Engg,   .   . ·1 ORM Office Building, near Pune Railway Statton, Pune Division, Centra~~:~ w?l 1 001 Tel.No.   020-2610   53 12 To Vicky   Lokare 24/1193   Balaji Nagar shahapur Lchalkaranji Ichalkaranji Pin   :416115 tj '5 ci~ ci  ~  cit WP  (ct,  I  Q)ct,  I cf> I tt~ci  ti, ljU!l4'5t1,~ Far1ict>: 01-04-2026  Sub:   Information under   RTI   Act 2005- Case   of   Shri   Shri   Vicky Lokare  Ref:  1. RTI   application No. DRMOP/R/P/24/00107 <ltd. 28/03/2026. ********* In   connection with the above, it is_ inform   you   that, the required information sought by you   pertains   to   Dy   CE/Constuction, Satara. Hence, your application   in   this regard is transferred   to   Dy   CE/Constuction, Satara   of   Pune Division under section 6(3) of RTI act, 2005. This is for   your information please.  ~\\1-'tl~\" DRM(Wks)Pune  I I  I",
    "originalFile": "evidence-1787556190106-rti-02-4-26-c.gov-.pdf",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-24T07:23:12.164Z",
    "updatedAt": "2026-08-24T07:23:12.164Z"
  }
];
