// सरकारी कागदपत्रे व पुरावे — edited via admin.html "सरकारी कागदपत्रे" tab.
// summary text is ADMIN-REVIEWED. extractedText (OCR) is used for search only.
const EVIDENCE_DOCS = [
  {
    "id": "ev-1787383568850",
    "title": "RTI 12-8-26 (C.Gov)",
    "category": "Railway / Government Letters",
    "date": "12.08.2026",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "केंद्रीय रेल्वेच्या मुख्य प्रशासकीय अधिकाऱ्यांनी (बांधकाम) दिलेलं RTI उत्तर. यात नमूद आहे: हातकणंगले–इचलकरंजी नवीन रेल्वे मार्ग (8 किमी) 2017-18 च्या Pink Book मध्ये समाविष्ट होता. या प्रकल्पाचा Detailed Project Report (DPR) रेल्वे बोर्डाकडे 02.01.2020 रोजी सादर करण्यात आला — खर्च ₹180.73 कोटी व ROR (-12.73%). प्रकल्प अद्याप रेल्वे बोर्डाच्या तपासणीत (scrutiny) असून मंजूर झालेला नाही, त्यामुळे पुढील तपशील अद्याप शेअर करता येत नाहीत असं उत्तरात नमूद आहे.",
    "extractedText": "--- पान 1 ---\n—\nCENTRALRAILWAY\n« IND;\n$F ao Sy Office of the\n(4 ERIE Chief Administrative Officer (Const.)\nSe. 6\" floor, New Administrative Building\nSi il D.N. Road, CSMT, Mumbai-400 001\nNo. EW/106/RT1/2026/0L-295 Date: - 12.08.2026\nShri Vicky Manisha Balu Lokare\nSub: Information required under Section 6(1) of the RTI Act 2005.\nRef: Online RTI application No. CRAIL/R/T/26/00731 dated 22.07.2026.\nhocks\nर With reference to the above, the information available in Central Railway Construction\nOrganization for Hatkanangale -Ichalkaranji Railway project is given as under: -\nInformation Sought\n\n1 Please provide the certified copies of the | The work of Hatkanangale -\nofficial file notings and processing history of | Ichalkaranji new Railway line (8Km)\nthe Detailed Project Report (DPR) for the | appeared in the Pink Book of 2017-18.\nHatkanangale-Ichalkaranji New BG line which | The Detailed Project Report (DPR) of\nwas submitted to the Railway Board by the | the said project was submitted to the\nCentral Railway Construction Wing in the year | Railway Board on 02.01.2020, ata cost\n2018. प of Rs. 180.73 crore & ROR (-12.73%).\n\nThe same is under scrutiny of Railway\nBoard.\n\nProject is not sanctioned yet, hence\ndetails cannot be shared.\n\n2 As per the official Twitter announcement by | Under the RTI Act, public authorities\nCentral Railway dated 11 June 2017 the | are not obligated to answer questions\nfoundation stone for the Final Location Survey | that seek explanations, reasons,\nof this line was laid by the then Minister of | opinions, or justifications for actions\nRailways. Please state the specific technical or | or decisions. The Act focuses on\nfinancial reasons why the Railway Board has | providing access to information in the\nnot granted final sanction to this project even | form of records, documents, etc,\nafter 8 years. rather than interpretations or\n\nopinions.\nPlease provide copies of any correspondence | Project is not sanctioned yet, hence\nor official remarks exchanged between the | details cannot be shared.\nRailway Board and NITI Aayog or the Ministry\nof Finance regarding the fund allocation. for\nthis specific Hatkanangale-Ichalkaranji rail\nlink.\n\n4 Please intimate whether this project is | The work of Hatkanangale-\ncurrently under consideration for inclusion in | Ichalkaranji new Railway line (8Km)\nthe upcoming Pink Book or Budgetary | appeared in the Pink Book 0f2017-18.\nAllocation. What is the current official status of | The Detailed Project Report (DPR) of\nthis project file in the Railway Board? the said project was submitted to the\n\nRailway Board on 02.01.2020, ata cost\nof Rs. 180.73 crore & ROR (-12.73%).\nThe same is under scrutiny of Railway\nBoard.\n(scanned with OKEN Scanner\n\n--- पान 2 ---\nPeriod to which information relates: June 2017 | The work of ) Hatkanangale-\nto May 2026. Ichalkaranji new Railway line (8Km)\nappeared in the Pink Book of 2017-18.\nThe Detailed Project Report (DPR) of\nthe said project was submitted to the\nRailway Board on 02.01.2020, ata cost\nof Rs. 180.73 crore & ROR (-12.73%).\nThe same is under scrutiny of Railway\nBoard.\nFormat of Information: Certified Copies via | Project is not sanctioned yet, hence\nRegistered Post or Online RTI Portal. | details cannot be shared.\nThis is for your information please.\nIf you are not satisfied with this information, appeal to the above lies with the 1st Appellate\nAuthority, within 30 days, from the date of receipt of this communication.\nThe name and address of the First appellate Authority are given Below: -\nChief Engineer (Construction) South,\nFirst Appellate Authority,\nCAO (C)’s Office, NAB Bldg.,\n6th Floor, D.N. Road,\nCST Mumbai-400 001.\n3 5\noii\nDy.\\CE(C)PLG & CPIO\nRly. No. - 022674-54310\nEmail- dycecpl@gmail.com\n(scanned with OKEN Scanner",
    "originalFile": "evidence-1787383566049-rti-12-8-26-c.gov-.pdf",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-22T07:26:08.850Z",
    "updatedAt": "2026-08-22T07:26:08.850Z"
  },
  {
    "id": "ev-1956-loksabha",
    "title": "लोकसभा प्रश्न क्र. 1205 — Ichal-Karanji ते Kolhapur-Miraj रेल्वे जोडणी (19 डिसेंबर 1956)",
    "category": "Railway / Government Letters",
    "date": "19.12.1956",
    "authority": "लोकसभा (Lok Sabha), भारत सरकार",
    "referenceNumber": "प्रश्न क्र. 1205, Written Answers पान 1799-1800",
    "tags": [
      "1956",
      "Lok Sabha",
      "Parliament",
      "Historical",
      "Earliest Record"
    ],
    "summary": "खासदार श्री. कजरोळकर यांनी लोकसभेत विचारलेला प्रश्न क्र. 1205 (19 डिसेंबर 1956, Written Answers, पान 1799-1800), शीर्षक: \"Railway Connection from Ichal-Karanji to Kolhapur-Miraj Line\". प्रश्न: महाराष्ट्र चेंबर ऑफ कॉमर्स, पुणे यांच्याकडून सरकारला असं निवेदन मिळालं आहे का, की कोल्हापूर-मिरज दरम्यान टाकल्या जाणाऱ्या ब्रॉडगेज मार्गाला हातकणंगल्याऐवजी इचलकरंजीशी जोडावं (इचलकरंजीच्या औद्योगिक व व्यावसायिक महत्त्वामुळे)? रेल्वे व वाहतूक उपमंत्री (श्री. अळगेसन) यांचं उत्तर: (अ) होय, असं निवेदन मिळालं आहे. (ब) कोल्हापूर-मिरज मीटरगेज मार्गाच्या ब्रॉडगेजमध्ये रूपांतरणासाठी प्राथमिक अभियांत्रिकी व वाहतूक सर्वेक्षणाचा अंदाज मध्य रेल्वेकडून मागवण्यात आला असून, हातकणंगल्याऐवजी इचलकरंजीला जोडण्याचा मुद्दा त्या सर्वेक्षणादरम्यान विचारात घेतला जाईल असं नमूद केलं आहे.",
    "extractedText": "Railway Connection from Ichal-Karanji to Kolhapur-Miraj Line. 1205. Shri Kajrolkar: Will the Minister of Railways be pleased to state: (a) whether a representation has been received by Government from the Maharashtra Chamber of Commerce, Poona, requesting to connect Ichal-Karanji instead of Hathkanangale to the broad-gauge line to be laid between Kolhapur and Miraj on account of the industrial and commercial importance of Ichal-Karanji; and (b) if the reply to part (a) be in the affirmative, what steps Government propose to take in the matter? The Deputy Minister of Railways and Transport (Shri Alagesan): (a) Yes. (b) An estimate for Preliminary Engineering and Traffic Surveys for conversion of Kolhapur Miraj M.G. section into B.G. has been called for from the Central Railway. The question of connecting Ichal-Karanji instead of Hathkanangale has been noted for consideration during the survey.",
    "status": "published",
    "version": 2,
    "previousVersions": [],
    "originalFile": "evidence-1956-lok-sabha-reference.pdf",
    "createdAt": "2026-08-22T13:07:48.131Z",
    "updatedAt": "2026-08-26T01:32:12.835Z"
  },
  {
    "id": "ev-1929-story-of-ichalkaranji",
    "title": "The Story of Ichalkaranji (1929) — H. George Franks — रेल्वे मार्गाचा सर्वात जुना ज्ञात उल्लेख",
    "category": "Other Evidence",
    "date": "1929",
    "authority": "H. George Franks (लेखक) — Scottish Mission Industries, Poona (प्रकाशक)",
    "referenceNumber": "Chapter VIII, पान 133–134",
    "tags": [
      "1929",
      "History",
      "Book",
      "Miraj-Kolhapur Railway",
      "Earliest Reference",
      "Narayanrao Babasaheb"
    ],
    "summary": "या पुस्तकाच्या आठव्या प्रकरणात (पान 133 च्या शेवटी सुरू होऊन 134 वर पूर्ण होणाऱ्या वाक्यात) असं नमूद आहे की इचलकरंजीच्या राजधानीला मिरज-कोल्हापूर रेल्वेशी एका शाखा मार्गाने जोडण्यासाठी काही काळापासून जोमदार प्रयत्न सुरू होते, जेणेकरून या समृद्ध खोऱ्यातील व्यावसायिक मालाची सुलभ ने-आण करता येईल. मूळ इंग्रजी वाक्य: \"for some time vigorous efforts have been made to connect the capital of Ichalkaranji with a branch line to the Miraj-Kolhapur Railway, which would open facilities for easy transhipment of commercial goods from the rich valley in which the capital town is situated.\" — सध्या उपलब्ध पुराव्यांमधील हा रेल्वे जोडणीच्या मागणीचा सर्वात जुना ज्ञात संदर्भ आहे (1956 च्या संसदीय प्रश्नापेक्षाही जुना).",
    "extractedText": "",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "originalFile": "evidence-1929-story-of-ichalkaranji.pdf",
    "createdAt": "2026-08-25T10:06:09.593Z",
    "updatedAt": "2026-08-25T10:06:09.607Z"
  },
  {
    "id": "ev-2015-karad-belgaum-proposal",
    "title": "कराड–इचलकरंजी–निपाणी–बेळगाव प्रस्तावित नवीन रेल्वे मार्ग — सर्वेक्षण तपशील व लोकप्रतिनिधी/नागरी संस्था पाठिंबा पत्रे (2015-16)",
    "category": "Railway / Government Letters",
    "date": "2015-2016",
    "authority": "विविध — इचलकरंजी रेल्वे कृती समिती, आमदार (महाराष्ट्र व कर्नाटक), विविध नगरपरिषदा/महानगरपालिका",
    "referenceNumber": "बहुविध पत्रे — तपशील सारांशात",
    "tags": [
      "Karad-Belgaum",
      "191.9 किमी",
      "Nipani",
      "Islampur",
      "Sankeshwar",
      "2015",
      "Support Letters",
      "Alternate Proposal"
    ],
    "summary": "⚠️ महत्त्वाची सूचना: हा प्रस्ताव सध्याच्या History/Project Status पानांवरील हातकणंगले–इचलकरंजी 8 किमी शाखा मार्गाच्या DPR (2017/2020) पेक्षा पूर्णपणे वेगळा आहे — गोंधळ टाळण्यासाठी वेगळा ठेवला आहे.\n\nहा एक मोठा, स्वतंत्र प्रस्तावित नवीन रेल्वे मार्ग आहे: कराड–इचलकरंजी–निपाणी–बेळगाव (एकूण 191.9 किमी — महाराष्ट्रात 94.6 किमी, कर्नाटकात 97.3 किमी). सर्वेक्षण तपशील: Take-off Point — Shenoli Yard (पुणे-मिरज मार्गावर); Meeting Point — Sambre Station (मिरज-बेळगाव मार्गावर); एकूण 21 स्थानके (4 अस्तित्वात: कराड, शेणोली, सांबरे, बेळगाव; 17 प्रस्तावित: तांबवे, इस्लामपूर, वाळवा, आष्टा, दुधगाव, नेज, इचलकरंजी, हुपरी, कागल, आडी, निपाणी, कणगला, संकेश्वर, हलकर्णी, दड्डी, हंडिगणूर, काकती); निपाणी-कणगला दरम्यान 2.85 किमी लांबीचा 1 बोगदा; गेज 1676mm सिंगल लाईन; गती 60-110 किमी/तास.\n\n2015-16 मध्ये अनेक लोकप्रतिनिधी व स्थानिक स्वराज्य संस्थांनी रेल्वे मंत्री सुरेश प्रभू व पंतप्रधान नरेंद्र मोदी यांना हा मार्ग मंजूर करण्याची विनंती करणारी पत्रे पाठवली — इचलकरंजी रेल्वे कृती समिती, आमदार सुरेश हाळवणकर (इचलकरंजी), आमदार शिवेंद्रसिंहराजे भोसले (सातारा), आमदार शशिकला जोल्ले (निपाणी, कर्नाटक), इस्लामपूर नगरपरिषद, आष्टा नगरपरिषद, निपाणी नगरपालिका (कर्नाटक), संकेश्वर नगरपरिषद (कर्नाटक), बेळगावी महानगरपालिका, कराड नगरपरिषद. पत्रांमध्ये नमूद अंदाजित खर्च ₹2100 कोटी (एका पत्रानुसार — हा आकडा DPR सारखा अधिकृत दस्तऐवज नाही, त्यामुळे पडताळणी आवश्यक).",
    "extractedText": "Karad Belgaum Railway Proposal. Salient features of the proposed new line: Route - Karad Belgaum via Nipani. Gauge - 1676mm (Single Line). Ruling Gradient - 1:150 in Plain terrain, 1:80 in Ghat Section for length of 1.5 Kms. Length in Kms - 191.9km (94.6 km in Maharashtra and 97.3 km in Karnataka). Speed - 60kmph for Ghat section and 110kmph for sectional length other than Ghat section. Take off Point - Shenoli Yard on Pune-Miraj section of CR. Meeting Point - At Sambre Station on MRJ end MRJ-Belgaum Section of SWR Rly. Nos of stations - 21 Nos. Existing Stations - Karad, Shenoli, Sambre, Belgaum. Proposed Stations - Tambhave, Islampur, Walva, Ashta, Dudhgaon, Nej, Ichalkaranji, Hupari, Kagal, Adi, Nipani, Kanagala, Sankeshwar, Halkarni, Daddi, Handignur, Kakati. Tunnels - 1 Nos of length 2.85 kms near Nipani from km 117.45 to 120.30 between proposed Nipani and Kanangala station. Support letters to Railway Minister Suresh Prabhu and PM Narendra Modi from Ichalkaranji Railway Kruti Samiti, MLA Suresh Halwankar, MLA Shivendrasinghraje Bhosale, MLA Shashikala Jolle Nipani, Islampur Nagarparishad, Aashta Nagarparishad, Nipani City Municipal Council, Sankeshwar Town Municipal Council, Corporation of the City of Belagavi, Karad Nagarparishad, dated between October 2015 and December 2015.",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "originalFile": "evidence-2015-karad-belgaum-railway-proposal.pdf",
    "createdAt": "2026-08-27T03:52:09.921Z",
    "updatedAt": "2026-08-27T03:52:09.935Z"
  },
  {
    "id": "ev-2026-mp-mane-letter",
    "title": "खासदार धैर्यशील माने यांचे रेल्वे मंत्र्यांना पत्र — हातकणंगले-इचलकरंजी मार्ग शीघ्र पूर्ण करण्याची विनंती (22 जुलै 2026)",
    "category": "Railway / Government Letters",
    "date": "22.07.2026",
    "authority": "श्री. धैर्यशील संभाजीराव माने, खासदार (लोकसभा) — मा. श्री. अश्विनी वैष्णव, रेल्वे मंत्री, भारत सरकार यांना",
    "referenceNumber": "जा.क्र. डीएसएम/३८/२०२६ — रेल्वे बोर्ड प्राप्ती शिक्का: 04 AUG 2026",
    "tags": [
      "2026",
      "MP Letter",
      "Dhairyasheel Mane",
      "Ashwini Vaishnav",
      "Karad-Belgaum",
      "Pink Book",
      "GST",
      "Budget"
    ],
    "summary": "खासदार धैर्यशील संभाजीराव माने यांनी रेल्वे मंत्री अश्विनी वैष्णव यांना लिहिलेलं अधिकृत पत्र — हातकणंगले-इचलकरंजी 8 किमी रेल्वे मार्ग शीघ्रतेने पूर्ण करण्यासाठी सहकार्याची विनंती. यातील महत्त्वाचे मुद्दे:\n\n🔗 अत्यंत महत्त्वाची स्पष्टता: \"हातकणंगले–इचलकरंजी रेलमार्ग जो मात्र ८ कि.मी. का है, यह रेलमार्ग कराड-बेलगाम (१९१ किमी) रेलमार्गका हिस्सा है\" — म्हणजे हा 8 किमी मार्ग स्वतंत्र नसून कराड-इचलकरंजी-निपाणी-बेळगाव या मोठ्या 191 किमी प्रकल्पाचाच भाग आहे. 2011 मध्ये कराड-बेळगाव मार्गाच्या सर्वेक्षणाला मंजुरी मिळाली, आणि 2013 मध्ये मध्य रेल्वे, पुणेने सर्वेक्षण पूर्ण करून अहवाल रेल्वे बोर्डाकडे पाठवला. भविष्यात कराड-बेळगाम मार्गाला मंजुरी मिळाली तर हातकणंगले-इचलकरंजी मार्ग आपोआप त्याला जोडला जाईल असं नमूद.\n\n📅 अर्थसंकल्पीय इतिहास: 2017 च्या अर्थसंकल्पात ₹150 कोटींची तरतूद व 2017-18 मध्ये ₹10 कोटी वितरित; भूमिपूजन 11.06.2017 रोजी तत्कालीन रेल्वेमंत्री सुरेश प्रभू यांच्या हस्ते; 2019-20 मध्ये टोकन ₹10,000 तरतूद व ₹10 लाख वितरित; 5 जुलै 2019 रोजी रेल्वे विभागाच्या Pink Book मध्ये समावेश; ⚠️ या पत्रात असंही नमूद आहे की या मार्गाचं सर्वेक्षण मध्य रेल्वे, पुणेने ऑगस्ट 2018 मध्ये पूर्ण करून DPR रेलभवनला पाठवला — ही तारीख साईटवर आधीच नोंदवलेल्या 30.11.2017 (मूळ DPR) व 02.01.2020 (सुधारित DPR) या तारखांशी पूर्णपणे जुळत नाही, त्यामुळे ही एक Conflicting Record आहे — पुढील पडताळणी आवश्यक.\n\n😞 अलीकडची निराशा: 2020-22 च्या अर्थसंकल्पात केवळ ₹1,000 (नाममात्र टोकन) वितरित करण्यात आले, अपेक्षित मुख्य निधी मिळाला नाही.\n\n💰 आर्थिक महत्त्व: पत्रानुसार इचलकरंजीतील कापड उद्योग, स्पिनिंग मिल, सिमेंट, कच्चा माल, पॅकिंग मटेरियल, कोळसा इत्यादींमधून दरवर्षी अंदाजे ₹5,200 कोटी GST भरला जातो.",
    "extractedText": "Dhairyasheel S. Mane, Member of Parliament - Loksabha. Member: Standing Committee on Home Affairs, Consultative Committee on Ministry of Textiles. Ja.Kr. DSM/38/2026, Dt. 22.07.2026. To: Shri Ashwini Vaishnav, Railway Minister, Government of India, New Delhi. Subject: Hatkanangale-Ichalkaranji 8 km railway line - regarding necessary cooperation for speedy completion. Received by Ministry of Railways (Railway Board) 04 AUG 2026. Content: 2017 budget provision of Rs.150 crore for approval, Rs.10 crore allocated 2017-18. 2019-20 token provision Rs.10,000, Rs.10 lakh allotted. Included in Pink Book 5 July 2019. Foundation stone laid by then Railway Minister Suresh Prabhu on 11-06-2017. Hatkanangale-Ichalkaranji railway line is part of Karad-Belgaum (191 km) railway line. In 2011 survey of Karad-Belgaum line was approved, in 2013 Central Railway Pune completed survey and sent report to Railway Board. If Karad-Belgaum line gets approval in future, Hatkanangale-Ichalkaranji will automatically be connected. Survey of this line completed by Central Railway Pune in August 2018, DPR report sent to Rail Bhavan. In 2020-22 budget only token Rs.1000 was allotted, causing disappointment. Ichalkaranji textile industry pays approximately Rs.5200 crore GST annually from textile, spinning mills, cement, raw materials, packing material, coal etc.",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "originalFile": "evidence-2026-mp-mane-letter.pdf",
    "createdAt": "2026-08-27T03:59:18.708Z",
    "updatedAt": "2026-08-27T03:59:18.725Z"
  },
  {
    "id": "ev-1965-tarun-bharat",
    "title": "तरुण भारत वृत्त — इचलकरंजी रेल्वेसाठी पालिकेचा 1965 चा ठराव",
    "category": "Photos / Scanned Documents",
    "date": "1965 (नेमकी मासिक तारीख अस्पष्ट — पत्रिकेवर फक्त \"20 नोव्हेंबर\" दिसतं, वर्षाचा अंक अस्पष्ट)",
    "authority": "तरुण भारत (वृत्तपत्र)",
    "referenceNumber": "",
    "tags": [
      "1965",
      "Municipal Resolution",
      "Tarun Bharat",
      "Newspaper",
      "Miraj-Kolhapur Broad Gauge"
    ],
    "summary": "तरुण भारत वृत्तपत्रातील बातमी — मथळा: \"इचलकरंजीत रेल्वे येण्यासाठी पालिकेचा 1965 ला ठराव\". उपमथळा: \"मिरज-कोल्हापूर रेल्वेलाईन ब्रॉडगेज करताना इचलकरंजी रेल्वे स्टेशन : रेल्वे खात्याकडून मिळाले होते आश्वासन\". बातमीत इचलकरंजी नगरपालिकेने 1965 साली रेल्वे जोडणीसंदर्भात ठराव पारित केल्याचा आणि मिरज-कोल्हापूर मार्गाच्या ब्रॉडगेज रूपांतरणावेळी इचलकरंजी स्टेशनबाबत रेल्वे खात्याकडून आश्वासन मिळाल्याचा उल्लेख आहे. सोबत तत्कालीन नगरपालिका पदाधिकाऱ्यांचा फोटो व यादीही आहे (5 जुलै 1961 रोजी निवडून आलेले सदस्य असं नमूद). ⚠️ प्रामाणिक मर्यादा: वृत्तपत्र कात्रणाच्या फोटोतील सर्व बारीक मजकूर (उदा. नेमका ठराव क्रमांक, पूर्ण तारीख) स्पष्टपणे वाचता आलेला नाही — मथळा व मुख्य आशय स्पष्ट आहे.",
    "extractedText": "Tarun Bharat newspaper clipping. Headline: Ichalkaranjit railway yenyasathi palikecha 1965 la tharav (Ichalkaranji Municipal Council 1965 resolution for railway to come to Ichalkaranji). Subheadline: Miraj-Kolhapur railway line broad gauge karताना Ichalkaranji railway station - railway khatyakadun milale hote ashwasan (While converting Miraj-Kolhapur line to broad gauge, assurance was received from railway department regarding Ichalkaranji station). Includes photo and list of municipal council members elected 5 July 1961.",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "originalFile": "ichalkaranji-railway-historical-1965-resolution.jpg.jpg",
    "createdAt": "2026-08-27T09:31:59.877Z",
    "updatedAt": "2026-08-27T09:31:59.889Z"
  },
  {
    "id": "ev-1787979817309",
    "title": "WhatsApp Image 2026 08 29 at 10.32.34 AM (1)",
    "category": "Other Evidence",
    "date": "23/01/2016",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nअमल HBC महाडिक\nशा) झडे ॥ वि.स.स. कोल्हापूर (दक्षिण) ॥\nv3 \\ # WW \" आंफिल २ ५२८, ई वार्ड, EGA, व्यापारी पेठ, कोल्हापूर.\nki meng i on) p कोल्हापूर आफिस : (०२३१) २६५५७७२, २६५७१५२, फॅक्स-२६५३२३९.\nमहाराष्ट्र विधानसभा शिरोली आंफिस ; (०२३०) २४६१००२ / ३ /%/y फॅक्स - २ ४६१००६,\nनिवास : HEAR १०७, शिरोली (पुलाची), ता. हातकणंगले. —_— RIT काल्हापूर-४१६ १२२.\nमोबाईल — rw +38 ९४२२०४७४७४. email : amal.mahadik9@gmail.com\nपना. /02/ (0 /2016 दि.23/01/2016\nप्रति,\nगा.ना..श्री.सुरेशजञजी प्रभु\nरेल मंत्री,भारतल TRB,\nनई दिल्ली.\nदिष्यय : ORS -इच्व्नकरंजी-निपाणी-बेलगाम इस नये रेल मार्गव्ही\nमंजुरी मिलने हेतु\nमहोदय,\nच्छिराड-इचलव्करंञी-निपाणी-बेलगाम इस नये रेल मार्ग व्ही\nUTE हो ऐसी इस चिभागट्छे TL लोगॉव्ही बहुत वर्षोसे मांग थी |\nSA HARES वञजहसे पूर्व रेल मंत्रीजीने चार वर्ष पहले रेल ब्जञेटमे\nSTD मंजुरी दी | दो वर्ष पूर्व इस नये रेल मार्ग व्हा सर्व्हे पुरा हुआ हे |\nमध्य रेल पुणे व्ही ओरसे SAD! जानव्ठारी रेल बोर्डव्छो भेजी हे ।सव्हे\nपुरे EEA इस मार्ग व्छे SEE सभी शहर क्ठे लोगॉमे खुषी आयी है।\nचह नया रेल मार्ग 191 कव्ि.मी. व्हा है,ओऔर इसे २१०० करोड\nखर्चव्छा अनुमान है | इस रेलमार्गव्े बननेसे १७ नये oy तथा शहर\nआपसमे FI तथा eg २०लाख नये mh सुरक्षित तथा\nआरामदायी यात्रा व्र पार्येगे | ट्रान्सपोर्टेशनव्ठे लिए वम Fest\nअच्छी Fete Asien प्राप्त्‌ होगी | और इससे रेलव्छोभी निश्‍चीत\nBUA FBT होगा | THE इस नये मार्ग पर THE ऐसे शहर हे जो\nओद्योगिक क्षेत्रमे भारतमे महत्वपूर्ण शहर माने जाते है ।॥पश्‍चिम\nम्हाराण्ट्रको हर क्षेत्रमे महत्वपूर्ण माना जाता है । उद्योग या खेती\nहो,या अनेकविध उत्पादन हो Agi सहव्ठार FEN वजहसे अनेक\nशुगरमिल ,स्पिनींग Brae माध्यमसे ET व्यापास्वृध्दी हो रही हे |\nJET अनेव्क इजिंनिअरिंग तथा मेडीकल कॉलेज व्छे माध्यमसे सभी\nTEED छात्र शिक्षा प्राप्त करने आते है ।नये 3: मार्गसे इन Jaan)\nजादा सुविधाएं प्राप्त हो सकती है। पुरे भारत वर्ष मॅ महाराष्ट्र एक\nऐसा राज्य है जो iz व्छो BR वे BUR Hatters रेव्हेन्यू देता है । डस\nसंपन्नता = TASTE इस्र विभागमे Imray न होने व्ही वजहसे सब्व्छो\nअसुविधाऑव्ठछा सामना BIEN पड रहा है |\n",
    "originalFile": "evidence-1787979794495-whatsapp-image-2026-08-29-at-10.32.34-am-1-.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787979829028",
    "title": "WhatsApp Image 2026 08 29 at 10.32.34 AM",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\n(चन ल) शिवाजीराव नाईक\n3 | ह आमदार, शिराळा.\n4 ATR (0233) २३२६७००\nमहाराष्ट्र विधानसभा ls शर शिराळा (०२३४५) २७११०० / २७२८१८\nमो. : ९४२३०३६७०० Email - shivajiraonaik99@gmail.com\nDE NET A isc novi\n8 निवास: “पार्वती” विश्‍वास होसिंग सोसायटी, सिव्हील हॉस्पिटल नजिक, सांगली ४१६४१६ m0\nदिनांक : :२९/१२ /२०१५\nप्रति,\nमा. सुरेशजी प्रभुसो,\nरेल्वेमंत्री भारत सरकार ,\nक नवी दिल्ली. र\nविषय : कराड-इचलकरंजी--निपाणी-बेळगांव रेल्वे मार्गास केंद्र शासनाकडून निधी\nमिळणेबाबत.\nमहोदय,\nकराड-इचलकरंजी-निपाणी-बेळगांव रेल्वे मार्गाचा सर्व्हे तीन वर्षांपूर्वी पूर्ण झाला आहे\nहे आपण जाणताच. या नविन रेल्वे मार्गामुळे महाराष्ट्र व कर्नाटक या दोन्ही राज्यांना माल वाहतूक\nव प्रवासासाठी चांगला नविन पर्याय उपलब्ध होणार आहे. या रेल्वे मार्गामुळे दोन्ही राज्यातील\nउद्योग व्यवसाय व रोजगार वाढीसाठी मदत होणार आहे.\nगेल्या अनेक वर्षांपासून या भागातील नागरीकांची हा रेल्वे मार्ग व्हावा अशी आग्रही मागणी\nआहे. गेल्या तीन वर्षापूर्वी या रेल्वे मार्गाचा सर्व्हे झाल्यामुळे या मार्गाबाबत येथील लोकांच्या अपेक्षा\nवाढल्या आहेत. इचलकरंजी परिसर औद्योगिक, सहकार व शेती उत्पादनात अग्रेसर असल्यामुळे\nया ठिकाणच्या विकासास मोठा वाव आहे. त्यामुळे कराड-इचलकरंजी-निपाणी-बेळगांव रेल्वे\nमार्ग होणे अत्यंत गरजेचे आहे.\nकृपया कराड-इचलकरंजी-निपाणी-बेळगांव रेल्वे मार्गास केंद्र शासनाकडून भरीव\nनिधी उपलब्ध करुन देवून लवकरात लवकर हा रेल्वे मार्ग पूर्ण करण्यासाठी आपणाकडून विशेष\nप्रयत्न व्हावेत ही विनंती.\nकळावे.\nआपला स्नेहांकित,\nI:\nfre!\n(शिंबांजीराव नाईक)\n",
    "originalFile": "evidence-1787979817318-whatsapp-image-2026-08-29-at-10.32.34-am.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787979846087",
    "title": "WhatsApp Image 2026 08 29 at 10.32.28 AM (1)",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nसत्यमेब जेयते\nधनंजय महाडिक\nसंसद सदस्य, लोकसभा, कोल्हापूर (महाराष्ट्र)\nचेअरमन : भिमा सह. साखर कारखाना लि.\n\nजावक क्र. ०८६/ खाधमसंकाको/कार्या /२०१६ दि. २२,जानेवारी २०१६\nप्रती,\nमा. श्री. सुरेश प्रभुजी,\nरेल मंत्री, भारत सरकार,\nनई दिल्ली.\n\nसस्नेह नमस्कार |\n\nविषय : कराड-इचलकरंजी-निपाणी-बेलगाम रेलमार्ग को रेल बजट मे अंतिम मंजूरी मिलने के विषय\n\nमे...\nमहोदय,\nकराड-बेलगाम इस नियोजित रेल मार्ग का सर्व्हे दो साल पहिले पूरा हो चुका है | इसका रिपोर्ट रेल्वे\nबोर्ड को भेजा है | इस नये रेल मार्ग से अनेक नये ग्राम तथा शहर रेल मार्ग से GS | इसलिए स्थानीक\nनागरीको मे अपेक्षापूर्ती का माहोल है । इस कार्य मे आपका एव्‌म रेल विभाग का बडा सहयोग रहा है | आपको\nहार्दिक धन्यवाद! यह विहीत करते हुए अत्यंत खुशी होती है कि १७ नये ग्राम और शहर रेल मार्ग से जुडॅगे तथा\nअडोस पडोस के ५० छोटे गावोको इस रेल मार्ग का लाभ होगा | इस रेल मार्ग से शहर तथा गावोका शिप्रतासे\nविकास होने मे सहाय्यता मिलेगी | नये रोजगार उपलब्ध होगे |\nइस रेल मार्ग सै महाराष्ट-कर्नाटक तथ गोवा राज्य से माल लाने तथा ले जाने का कार्यविस्तार होगा\n\nऔर यात्रियोको आवागमन की सुविधा मिलेगी | भारतीय रेल की आय बढेगी कारण इचलकरंजी शहर कपडा\nउद्योग मे भारतवर्ष मे अग्रेसर शहर माना जाता है | साथ ही हुपरी चांदी उद्योग मे एक प्रमुख शहर के रुप मे\nप्रख्यात है | तथा कागल मे अनेक नये उद्यम स्थापीत व विकसीत हो रहे है । कर्नाटक के निपाणी और\nआसपासके गावो मे तबाखू बडे पैमाने पर उत्पादीत होला है | नये १७ गांव एवम शहर जुडनेके कारण आसपासे\nके कही छोटे मोठे कसबो wd का विकास होनेकी नई राह मिलेगी |\n\nकरांड-इचलकरंजी- निपाणी-बेलगम १९१कि. मी का बताया जा रहा है । जिसमे महाराष्ट्र मे ९४.६\nकिगी. रेलमार्ग बनेगा, तथा महाराष्ट्र के इस्लामपूर -वाळवा-आष्टा-दुधगाव-नेज-कुंभोज-इचलकरंजी-हुपरी\nतथा कागल इत्यादी गांव erm से RN । कर्नाटक मे ९७.३ कि.मी. रेलमार्ग होगा और अडी-निपाणी-\nकणंगला-संकेश्‍वर-हलकर्णी--दड्डी-हडींगनूर और काकती इत्यादी गाव रेलमार्ग से जुडेगे | कराड तथा\nबेलगाम यह रेल्वे स्टेशन जक्शन होंगे । इस मार्ग के लिए Roo करोड का बजेट अनुमानित है यह नया\nरेलमार्ग मुंबई-बेगलोर-कॉरीडॉर के लिए भी अत्यंत महत्व की भुमिका निभायेगा ।\n\nऑफिस : २११३, इं वाडे, ताराराणी चौक, कोल्हापूर -४१६ ००५ (महाराष्ट्र) फोन (०२३१) २५३५५७७, २५३८०३४ फॅक्स : (०२३३१) २५३४६२७\nनिवास fom, २८६, ई वॉर्ड, महाडिक वसाहत, कोल्हापू' - ४१६ ००५ (महाराष्ट्र) फोन : (0२३१) २६५३६२१\n",
    "originalFile": "evidence-1787979829029-whatsapp-image-2026-08-29-at-10.32.28-am-1-.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787979858838",
    "title": "WhatsApp Image 2026 08 29 at 10.32.28 AM (2)",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\niin mn oy शिवेंद्रसिंहराजे भॉसले\nnnn gl . & . विधानसभा सदस्य\nमहाराष्ट्र विधानसभा महाराष्ट “ged ps\nप्रति, दि.०५/११/२०१५\nमा.ना.श्री.सुरेशजी प्रभुसो\nरेल मंत्री, भारत सरकार,\nनई दिल्ली.\nविषय : समुचित विकास के लिए कराड-इंचलकरंजी-निपाणी-बेलगाव रेल\nमार्ग को मंजूरी मिलने हेतू ...\nमहोदय, न\nकराड-इंचलकरंजी -निपाणी -बेलगाव इस रेल मार्ग का सव्हे तीन बरस पहले पूर्ण हुआ\nहै। इस र्मा का नक्षा हमे प्राप्त हुआ। TH को देखनेसे पता चला कि इस मार्गसे महाराष्ट्र तथा\nकर्नाटक के अनेक नये हहर तथा गाव रेल मार्ग से SE | इस मार्ग पर कुछ गाव तथा शहर ऐसे\nहै जो उद्योग क्षेत्रमे तथा व्यापार मे अपनी अलग पहचान रखते है। इस रेल मार्ग से उद्योग क्षेत्र\nको बढावा मिलेगा FATT इन शहरोमे उत्पादित होनेवाली चीजे बाहर भेजने के लिऐ नया सस्ता\nपर्याय रेल के माध्यम से उपलब्ध होगा। इससे तेजीसे विकास होगा तथा रेल को भी ट्रान्सपोर्टेशन\nके माध्यम से अधिक मुनाफा होगा।\n\nर आपने तैयार किया हुआ रेल मार्ग निश्‍चितही सराहणीय है। इस मार्ग से पश्चिम महाराष्ट्र\nतथा उत्तर कर्नाटक के कई हिस्से जुडणे मे सहाय्यता होगी। इस मार्ग पर रेल सेवा' अत्यंत\nआवश्यक | दुसरा फायदा यह है की इस मार्ग को बनाने से फासला याने कि.मी कम होंगे)\nडिझेल की बचत होगी, कराड तथा बेलगाव ये गांव जंगशन होंगे। इस रेल मार्ग से विकास मे गती\nआयेगी। विकास कार्य मे रेल की भूमिका सबसे प्रमुख है।\n\nअतःहम आपसे निवेदन करते है की इस रेल मार्ग को अंतिम मंजूरी देवे तथा इस मार्ग का\nनिर्माण जल्द से जल्द करवाके अनेक TUR रेल का सपना पूर्ण करनेंमे सहयोग करेंगे। यही\nविनम्र कामना करते है।\nसस्नेह... ! र र\n, द FP\n= Zo dw)\n",
    "originalFile": "evidence-1787979846088-whatsapp-image-2026-08-29-at-10.32.28-am-2-.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787979873043",
    "title": "WhatsApp Image 2026 08 29 at 10.32.28 AM",
    "category": "Other Evidence",
    "date": "20/99/2094",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nSANKESHWAR RAILWAY ACTION COMMITTEE\nSANKESHWAR, Dist : Belgaum, Karnataka\nHodegg पुड WIT BOWLES, Todezgg 2.39 (TFET)\nसंकेश्वर रेल्वे अॅँक्शन कमिटी, संकेश्वर जि.बेळगांव (कर्नाटक)\nee —  —\nCONVENOR: VILAS Y. GHORPADE Mobile N0.09742355452\n__subhashRoad, Sankeshwar- 591313 Dist: Belgaum, Karnataka State Road, Sankeshwar- 591 313 Dist : Belgaum, Karnataka State\nदिनांक : 20/99/2094\nप्रति,\nमान.श्री सुरेशजी प्रभु, :\nरेलमंत्री, भारत सरकार,\nरेलभवन,\nनई दिल्ली - ११० 00१.\nविषय : समुचित विकास के लिये कराड-इचलकरंजी-निपाणी-संकेश्वर-बेळगाव\nरेल मार्ग को मंजूरी मिलने हेतू, .\nमहोदय, 1 ;\nसप्रेम नमस्कार।\nकराड-इचलकरंजी-निपाणी-संकेश्वर-बेलगाम इस रेल मार्ग का सर्व्हे कुछ समय पुर्ण हुआ | इस मार्ग का नक्षा\nहमे प्राप्त हुआ। नकशे को देखने से पता चला की इस मार्ग से महाराष्ट्र तथा कर्नाटक (१९१ कि.मी) के अनेक नये शहर )\nतथा गाव रेलमार्ग से GEN इस मार्गपर कुछ गांव तथा शहर ऐसे है जो उद्योग क्षेत्रमे तथा व्यापार मे अपनी अलग\nपहचान रखते है। इस रेल मार्ग से उद्योग क्षेत्र को बढावा मिलेगा wid इन शहरो मे उत्पादित होनेवाला माल बाहर\nभेजने के लिये नया सस्ता पर्याय रेलके माध्यम से उपलब्ध होगा। इस से तेजीसे विकास होगा तथा रेल्वे को भी\nट्रान्सपोर्टेशन के माध्यम से अधिक मुनाफा होगा।\nआपने तैयार किया हुआ नया रेलमार्ग निश्‍चित ही. सराहनीय है। इस मार्ग से पश्‍चिम महाराष्ट्र तथा उत्तर\nकर्नाटक के कई इलाके जुडने मे सहायता होगी। इस मार्गपर रेल सेवा अत्यंत आवश्यक है। दुसरा फायदा यह की इस\nमार्ग को बनाने से फासला याने कि.मी. कम होंगे। डिझेल की बचत होगी। कराड तथा बेलगाम ये गांव जंगशन होंगे। इस\nरेल मार्ग से विकास मे गती आयेगी और यही हमारे प्रधानमंत्रीजी की हार्दिक इच्छा है। विकास कार्य मे रेलकी भुमिका\nसबसे प्रमुख है।\nअत: हम आपसे निवेदन करते है की इस रेल मार्ग को अंतिम मंजूरी देवे तथा इस मार्ग का निर्माण जल्द से\nजल्द करवा के हमारा अनेक ase रेलका सपना पुर्ण करनें मे सहयोग करेंगे। यही Re कामना करते है।\nधन्यवाद।\nआपका कृपाभिलाषी,\nA\nHT 101 COMMITTEE\nSa ka State )\n",
    "originalFile": "evidence-1787979858839-whatsapp-image-2026-08-29-at-10.32.28-am.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787979879792",
    "title": "WhatsApp Image 2026 08 29 at 10.32.29 AM (1)",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nग बान स जयंत राजाराम पाटील\nFER 4 ही विधानसभा\nTim 2 आह\nमहाराष्ट्र विधानसभा महाराषर\nजावक क्रमांक : दिनांक :\nजा.क्र. Cl /कॅण्ण वाळवा २४/१०/२०१५\nविषय :- महाराष्ट्र व कर्नाटक राज्याच्या नवीन कराड - इचलकरंजी -\nनिपाणी - बेळगांव रेल्वे मार्गास रेल्वे अर्थ संकल्पात मंजूरी\nमिळून निधी उपलब्ध होणेबाबत ......\nकराड - इचलकरंजी - निपाणी - बेळगांव ही महत्वाची शहरे\nजोडणाऱ्या नवीन रेल्वे मार्गाचा सर्व्हे झालेला आहे. महाराष्ट्र व कर्नाटक\nया दोन राज्यातून जाणाऱ्या या रेल्वे मार्गामुळे वरील शहरांचा सर्वांगीन\nविकास होणार आहे. सदरचा नवीन रेल्वे मार्ग होणेबाबत या परिसरातील\nरेल्वे कृती समिती सातत्याने पाठपुरावा करीत आहे.\nतरी कराड, इचलकरंजी, निपाणी, बेळगांव या शहरातील उद्योग\nधंदा वाढीच्या व दळणवळणाच्या दृष्टीने या रेल्वे मार्गास रेल्वे अर्थसंकल्पात\nमंजूरी मिळून निधी उपलब्ध होणेबाबत उचित सहकार्य व्हावे ही विनंती.\nआक hal)\nCo)\nमा.ना.श्री.सुरेश प्रभू,\nरेल्वे मंत्री, भारत सरकार,\nनवी दिल्ली.\n॥ कार्यालय: राजारामनगर, पोस्ट: साखराळे, तालुका: वाढवा, जिल्हा: सांगली पिन- ४१५ ४१४\n॥ दूरध्वणी: (०२३४२) २२०८६१ ते ६५ फॅक्स ०२३४२-२२१००९\n",
    "originalFile": "evidence-1787979873044-whatsapp-image-2026-08-29-at-10.32.29-am-1-.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787979899226",
    "title": "WhatsApp Image 2026 08 29 at 10.32.29 AM (2)",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nसौ. शुभांगी श्रीकांत च त बिरंजे इचलकरंजी नगरपरिषद, इचलकरंजी. न»\n' शुभा का = कार्यालय : B (0२३0) २४३५४६०, २४२१४५१ ते ५५\nनगराध्यक्षा, (93.400) Cs ७ निवास : १२/३१६, शिवपर्व, शिवाजीनगर, इचलकरंजी\nइचलकरंजी नगरपरिषद, इचलकरंजी, . मोबा Tne, swoon\nळा अ Sa oii Le —— ER VR Sa ss SG pl SENET 22 OE Ei\naE R24 0६0 १015\nप्रति,\nमा.श्री.नरेंद्र मोदीजी,\nपंतप्रधान, भारत सरकार,\nनई दिल्ली.\nविषय :- सर्व्हे किये गये कराड-इचलकरंजी-बेलगाम रेल मार्ग को रेल बजेट मे अंतिम मंजूरी\nमिलनेके विषय मे ।\nसंदर्भ :- भारतीय रेल अंतर्गत सर्व्हे टेंडर क्रं.मध्य रेल्वे खुली निविदा क्रं.डीवायसीइ (सी) पीए\n/ओसी ०९ दि.२८/२१/२०१९ उपमुख्य अभियंता (सी) मध्य रेल्वे पुणे (महाराष्ट्र के\nअनुसार के जानकारी)\nमा.महोदय, सप्रेम वंदे,\nकराड-इचलकरंजी-बेलगाम नये रेल मार्ग का सव्हेक्षण का काम पुर्ण हुआ है। इस रेल मार्ग पर\nइचलकरंजी शहर का समावेश हुआ। इचलकरंजी शहर का समावेश होने के कारण सभी इचलकरंजी\nवासियोमे खुशी का माहोल दिखाई दे रहा है। इस काम मे आपका एंबम रेल विभाग का विशेष योगदान\nमिला। आपको रेल्वे कृती समिती की ओर से धन्यवाद देते है। लगभग १७ गांव शहर इस रेल मार्गसे जुडेंगे\nइससे लाखो यात्रीयाको लाभ होगा। यह रेल मार्ग १९१ कि.मी.का बताया जा रहा है, और इसे २१०० करोड\nखर्च का अनुमान है।\nइचलकरंजी शहर महाराष्ट्र मे कोल्हापूर जिल्हे मे आता है | कपडा उद्योग मे भारतवर्ष मे प्रमुख शहर\nके नाम से जाना जाता है। इतना ही नही महाराष्ट्रका मँचेस्टर केहलाता है। ३ ते ३.५ लाख आबादी का यह\nशहर औद्योगिक क्षेत्र मे अल्पावधी मे प्रगतीपथ पर है। पश्‍चिम महाराष्ट्र मे सर्वांधिक रेव्हॅनुय भरनेवाला यह\nशहर है। भविष्य मे कॉटन टेक्सटाईल मार्केटींग मे अत्यंत महत्वपुर्ण शहर के रुप मे जाना जायेगा | यहॉ पर १\nलाख १० हजार पॉवरलूम्‌, ३५ हजार शटललेस लुम है। इसे संलग्न अन्य व्यवसाय भी है, जैसे सायझिंग\n४०० युनिट, प्रोसेस २५, तथा BE उद्योग बडे पैमानेपर है। यह इलका सहकार क्षेत्र मे अग्रेसर होनेसे यहॉ\nपर अनेक स्पिनिंग मिल तथा शुगर मिल की भी संख्या बडे पैमानेपर है।\nFER प्रती दिन लगभग देड करोड मिटर कपडा प्रती दिन बुना जाता है। इस उद्योग के लिये कच्चा\nमाल प्रती दिन २५० ये ३०० ट्रक मंगवाया जाता है। तथा पक्का बनाया हुआ माल लगभग २५० ट्रक प्रती दिन\n- अन्य राज्योमे भेजा जाता है। ऐसे औद्योगिक क्षेत्रो मे रहनेवाले इचलकरंजी शहर को रेल सेवा अनीवार्य है।\nऊपर दिये गये बातोंसे पता चलेगा की इतना बडा ट्रान्सपोर्टटेशन रेल को मिलेगा जिसे रेल की\nआमदनी मे बडोत्री होगी तथा स्थानिक उद्योग का विकास होगा । आप जानतेही है जो शहर रेल मार्गसे जुडे है\nवह अल्पावधी मे विकसीत होते है। इचलकरंजी शहर को रेल सुविधा मिलेने से इसकी अलग पहचान बनेगी ।\nइस नये नियोजीत रेल मार्ग से कर्नाटक तथा पश्‍चिम महाराष्ट्र के विकास के लिए निश्‍चित ही बढा योगदान\nमिलेगा | सद्यस्थिती मे कराड-बेलगाम जो मार्ग है उससे मुकाबले नये मार्ग के सफर का फासला याने २२\nकि.मी. कम होंगे | अनेक नये शहर तथा गाँव जुडे SEH | लाखो यात्रियोंको लाभ होगा इतनाही नही हुपरी\n",
    "originalFile": "evidence-1787979879793-whatsapp-image-2026-08-29-at-10.32.29-am-2-.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787979908410",
    "title": "WhatsApp Image 2026 08 29 at 10.32.29 AM",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nI\nPliny : Pap आमदार बाळासाहेब पांडुरंग पाटील\n4 | | | \\ 8 (कराड-उत्तर) जि. सातारा\nमहाराष्ट्र विधानसभा Perret\nजा क्र.६०७/२०१५ दिनांक :- १८/१०/२०१५\nप्रति -\nमा.श्री सुरेशजी प्रभुसो!,\nरेलमंत्री, भारत सरकार,\nनई दिल्ली.\nसप्रेम नमस्कार ।\nविषय :- नवे शहर तथा गांवोंको रेल सेवा उपलब्ध होने के लिये कराड-इचलकरंजी-\nनिपाणी-बेलगाम रेल्वे मार्ग को मंजूरी मिलें।\nसन्माननीय महोदय,\nकराड-इचलकरंजी-निपाणी-बेलगाम इस मार्गका सर्व्हे गत दो वर्ष पुर्ण हुआ | इस\nनियोजीत रेल मार्गपर हमारा गांव भी आता है । इससे यहाँके स्थानिक निवासीयोंमे बडी\nप्रसन्नता है । आपको एवम रेल्वे प्रशासनको हम शतशः धन्यवाद देते है । इस मार्गके लिये\nअनेक वर्षासे प्रयास हो रहा है ।\nमहाराष्ट्र तथा कर्नाटक राज्य के अनेक नये जिले तथा तहसिल इस नये रेल\nमार्गसे जुडेंगे। इससे यात्रींको लाभ मिलेंगाही उद्योग, व्यापार एवं खेती का विकास होनेमें\nविशेष रूप से मदत होगी ।\nउपर सुझाये गये इस रेल मार्ग का AL होनेसे हमारी बहुतसारी अशाए अंकुरीत\nहुयी है । आशा करते है की आप शीप्रही इस मार्ग को मंजूरी देकर अल्प समय मे ही इस\nनये रेल मार्ग का निर्माण करेंगे व विकास की नयी राह प्रदान करेंगे ।\nआपका अभिलाशी,\n(बाळासाहेब पाटील)\nसदस्य, महाराष्ट्र विधानसभा,\nकराड-उत्तर.\n प्रिवास,प्लॉटनं. २६०, मंगळवारपेठ, कराड. ४१५११० जि.सातारा. शा\nफोन : (०२१६४) निवास : २२०४४४, २२२१२२ फॅक्स : २२४१११ ऑफिस : (०२१६४) ६६१५००\nemail - amdbalasahebpatil@gmail.com ||\n",
    "originalFile": "evidence-1787979899227-whatsapp-image-2026-08-29-at-10.32.29-am.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787979921766",
    "title": "WhatsApp Image 2026 08 29 at 10.32.30 AM (1)",
    "category": "Railway / Government Letters",
    "date": "",
    "authority": "",
    "referenceNumber": "Date",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nShashikala A. Jolle Bharatiya Janata Party\nMLA- Nipani Karnataka\nPresident - Mahila Morcha w\nKarnataka State\n_—\nRef. No. Date : ००.८ 19०१5\nTo\nShri Suresh Prabhu Ji\nHon. Minister of Railways\nGovt. of India\nNew Delhi\nSub : Karad — Ichalkaranji — Nipani — Belagavi Railway Line.\nSir\n\nThe Survey of Karad — Belagavi Railway Line has taken place before two years. Its\nreport is also submitted to the Ministry of Railways. This line will connect 17 new towns and\n50 villages that will help the common people of this area. Due to this, Rail connectivity,\nfaster development of this region is also possible and even new Industries will arrive in the\nsurroundings.\n\nThis line will also make the transportation between three states Maharashtra,\nKarnataka and Goa faster and convenient. There are various industries in the surroundings\ne.g. Ichalkaranji -Textile, Hupri -Silver, Nipani —Tobacco, Kagal - MIDC ete. which will\nflourish more if this project comes through.\n\nThis Railway Line will also connect religious places in Maharashtra and Karnataka\nlike Bahubali, Kunthagiri, Vipashyana Kendra , Stawanidhi, Appachi Wadi, Aadi,\nRamteerth and also hill station Amboli.\n\nIn comparison with other states, Karnataka state has less Rail Communication. I am\nsure , you will personally look in to this matter positively and in the next budget will\nsanction Karad — Ichalkaranji — Nipani — Belagavi Rail Line.\n\nThanking you\nYours sincerely\nForni\nShashikala Jolle\nMLA — Nipani (Karnataka)\nCopy to,\nNl Sou. Shubhangi Shrikant Biranje\nPresident Railway kruti samiti & City Prisident\nIchalakaranji Nagarparishad, Ichalakaranji\nन\nOffice : Pattanshetti Buildina Rani Channamma Circle Ninani Tal - Chikodi Diet - Relaanm - 501237\n",
    "originalFile": "evidence-1787979908411-whatsapp-image-2026-08-29-at-10.32.30-am-1-.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787979940401",
    "title": "WhatsApp Image 2026 08 29 at 10.32.30 AM (2)",
    "category": "Railway / Government Letters",
    "date": "",
    "authority": "",
    "referenceNumber": "Date",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nRESIDENCE :\nSAMBHAJI Ti चि PATIL (ह BC-121, Jijau cottage,\nES & Malhotra Road,\nBelgaum South Constituency टे J) ce wre ee co og\nNTS Camp, Belgaum-590001 *\nM. : 9448147499\nEmail : slpatil9499@gmail.com\nRef. No. Date: 05 -//- 2015\nप्रती,\nमा.श्री. सुरेश प्रभु,\nरेल मंत्री, भारत सरकार,\nनवी दिल्ली.\nविषय: कराड-इचलकरंजी-निपाणी-बेलगाम रेलमार्ग को रेल बजट मे अंतिम\nमंजूरी मिलनेके विषय मे.\nमा. महोदय,\nसादर वन्दे, ४\nकराड-बेलगाम इस नियोजीत रेल मार्ग का सर्व्हे दो साल पहिले पूरा हो चुका है! इसका रिपोर्ट\nरेल्वे बोर्ड को भेजा है! इस नवे रेल मार्ग से अनेक नवे ग्राम तथा ग्हर रेल मार्ग से जुडेगे! इसलिए्‌\nस्थानीक नागरीको मे अपेक्षापूर्ती का माहोल है! इस कार्य मे आपका एवम रेल विभाग का बडा सहयोग\nरहा है! आपको हार्दिक धन्यवाद ! यह विहीत करते हुए अत्यंत wa होती है कि १७ नये ग्राम और we\nरेल मार्ग से जुडेगे तथा अडोस पडोस के ५० छोटे गावोको इस रेल मार्ग का AT होगा! इस रेल मार्ग\nसे शहर तथा गावोका शिप्रतासे विकास होने मे सहाय्यता मिलेगी। नये रोजगार उपलब्ध होगे!\nइस रेल मार्ग से महाराष्ट्र-कर्नाटक तथा गोवा राज्य से माल तथा ले जाने का कार्यविस्तार होगा\nऔर यात्रियोको आवागमन की सुवीधा मिलेगी! भारतीय रेल की आय बढेगी कारण इचलकरंजी जहर\nकपडा उद्योग मे भारतवर्ष मे अग्रेसर शहर माना जाता है! साथ ही हुपरी चांदी उद्योग मे एक प्रमुख शहर\nके रुप मे प्रख्यात है! तथा कागल मे अनेक नये उद्यम स्थापीत व विकसीत हो रहे है! कर्नाटक के निपाणी\nऔर आसपासके गावों मे तंबाखू बडे पैमाने पर उत्पादीत होता है! नये १७ गांव एवम wet जुडनेके कारण\nआसपास के कही छोटेमोठे कसाबो गांवो का विकास होनेकी नई राह मिलेगी!\nकराड-इचलकरंजी-निपाणी-बेलगाम १९१ कि.मी का बताया जा रहा है! जिसमे महाराष्ट्र मे ९४.६\nकि.मी रेलमार्ग बनेगा, तथा महाराष्ट्र के इस्लामपूर-वाळवा-आश्-दुधगाव-नेज-कुंभोज-इचलकरंजी-हुपरी\nतथा कागल इत्यादी गांव रेलमार्ग से जुडेगे! कर्नाटक मे ९७.३ कि.मी रेल मार्ग होगा और अडी-निपाणी-\nकणंगला-संकेश्वर-हलकर्णी-दड्डी-हंदीगनुर और काकती इत्यादी गाव रेलमार्ग से जुडेगे! कराड तथा\nबेलगाम यह रेल्वे स्टेशन WE होंगे! इस मार्ग के लिए २१०० करोड का बजेट अनुमानित है! यह नया\nरेलमार्ग मुंबई-बेगलोर-कारीडोर के लिए भी अत्यंत महत्व की भुमिका निभावेगा!\nकराड-इचलकरंजी-निपाणी-बेलगाम इस नये रेल मार्ग से कुछ तीर्थ क्षेत्र जुडेगे! जैसे\nइचलकरंजी के पास बाहुबली, कुंथगिरी, विपश्न्ना केंद्र, प्रभु श्री राम के पदस्पर्श से पावन रामलिंग,\nश्रीक्षेत्र धुळोबा, कागल के पास कनेरीमठ, आप्पाची वाडी, निपाणी के पास जैन समाज का प्रसिध्द :\nतिर्थक्षेत्र, स्तवनिधी क्षेत्रपाल तथा तिर्थकर भगवान अतिशय क्षेत्र तथा शिवजीका मंदीर संकेश्वर के पास\nपणा लआळत.-भाणए्ककळ्कळ्याळ्ा््ज्ाण्यफायाट्रला\n",
    "originalFile": "evidence-1787979921767-whatsapp-image-2026-08-29-at-10.32.30-am-2-.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787979954535",
    "title": "WhatsApp Image 2026 08 29 at 10.32.30 AM",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nfi PUY यशवंत सुर्यवंशी\nSag PI\n> a” - ७ नगराध्यक्ष,\n4 5 उरुण-इस्लामपूर नगरपरिषद. (जि.सांगली)\nसि ० 2 : कार्यालय (0२३४२) २२२०२३, २२२१५९\nमोबा : ९३७३५७८३२५\nप्रति,\nमा.श्री. सुरेशजी प्रभू,\nरेल्वेमंत्री,\nभारत सरकार, नवी दिल्ली.\nविषय - कर्नाटक एवं महाराष्ट्र राज्य के सर्वांगीण विकास के लिए कराड-\nइचलकरंजी-निपाणी-बेलगाम रेल मार्ग को मंजूरी मिलें।\nमाननीय महोदय, सादर वंदे,\nआप जानतेही है की कराड-इचलकरंजी-निपाणी-बेलगाम इस रेल मार्ग का सर्व्हे सेंट्रल रेल्वे पुणे\nकी ओरसे पुर्ण हुआ है । इस नये मार्ग से हमारे गांवकोही नहीं अपितु अन्य अनेक शहर गांवको लाभ\nहोगा | कर्नाटक तथा महाराष्ट्र राज्य इस नये रेल मार्ग के जुडनेसे इन UAH! यातायात के लिये\nनिश्‍चित ही लाभ होगा | इस ARTY महाराष्ट्र, कर्नाटक तथा गोवा इन राज्योंको पर्यायी नया (कम\nकि.मी. अंतरवाला) रेल्वेमार्ग उपलब्ध होगा | इस रेलमार्ग की मांग अनेक वर्षांसे होती आई है । यह\nरैलमार्ग नॅशनल हायवे 4 को समांतर रहने से भविष्य मैं लाभदायी सिध्द होगा, इतनाही नही मुंबई\nबँगलोर कॅरीडॉर के लिये भी महत्वपूर्ण रहेगा |\nआप स्वयंम जानतेही है की देश के विकास और व्यवसाय वृध्दी के लिए रेल कितनी\nमहत्वपूर्ण है | भारत सरकार का लक्ष्य देश का विकास ही है | मा. प्रधानमंत्रीजी मोदीजी हमेशा रेल\nका जिक्र करते है | देश की जनसंख्या एवं उद्योग जितने बढे है, उतने पैमाने पर नये रेलमार्ग\nविकसित नही हुवे है यह सत्यता है | लेकीन आप की ओर से नये WAR बनाने के लिये विशेष\nप्रयास किये जा रहे है ।\nहमारा आपसे अनुरोध है की आप हमेन सुझाये हये कराड-इचलकरंजी-निपाणी-बेलगाम इस\nरेलमार्ग को रेल बजेट मॅ मंजूरी देंगे तथा शीघ्रतासे यह मार्ग पुर्ण FOF सहयोग करेंगे!\noe ण\n(सुभाष प सुर्यवंशी)\nनगराध्यक्ष\nइस्लामपूर नगरपरिषद\n",
    "originalFile": "evidence-1787979940402-whatsapp-image-2026-08-29-at-10.32.30-am.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787979963088",
    "title": "WhatsApp Image 2026 08 29 at 10.32.31 AM (1)",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nसत्यमेव जयते\nChh. Udayan Raje Bhonsle\nMEMBER OF PARLIAMENT\n(LOK SABHA)\n\nON-IMP/  /W.S/15\nDate:-18 Oct.,15\n\nTo,\n\nHon. Shri. Suresh Prabhu,\n\nMinister of Indian Railway,\n\nRail Bhavan,\n\nNew Delhi.\n\nSub:-Building up a new railway track between Karad, Dist —\n\nSatara (Maharashtra) and Dharwad, Dist-Dharwad (Karnataka)\nRespected sir,\n\n1 wish to bring the above matter for your kind consideration. By rail the\ndistance between Karad and Kolhapur is 124kms and it takes near about 2.30 hours\nto Kolhapur. The distance between these two cities by NH-4 is only 70kms, which\nis journey of 1 hour. The distance between Kolhapur and Dharwad(Karnataka), if\ntraveled by train is about 308kms via Khanapur, Londha, Stations etc. If the new\ntrack is planned between Karad and Dharawad via Nipani, Belgum which will save\na journey of 180kms. Pune and Dharawad these two important LT. cities can be\nconnected by nearest distance, which can help for industrial growth of both the\ncities.\n\nWe often discuss about the saving of fuel and time, which is need of hour.\nTherefore, I request you to please instruct the concerned officers/department to\nlook into this proposal and do the needful survey of the proposed new track as early\nas possible.\n\nOnce again 1 request you to please look into this matter and make the\nnecessary budget provision for this survey work in the railway budget for 2010-\n2011.\n\nThanking you,\nYours Faithfully\nde — ~\nimant Chhatrapati je Bhonsle)\nMember of Parliament, SATARA\n",
    "originalFile": "evidence-1787979954536-whatsapp-image-2026-08-29-at-10.32.31-am-1-.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787979975047",
    "title": "WhatsApp Image 2026 08 29 at 10.32.31 AM",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nCosi अड. कु. विद्याराणी घनःश्याम साळुंखे\nचा» 2 B.Com. LLB.\nकै > अध्यक्षा,\nEN 7) निवास : ३९१, रविवार पेठ, कराड. ४१५ 990. कराड नगरपरिषद, कराड\n\nHL मोबा. ९९२२४३९६४३, ९४२२४०१०४१. i\n\nनिवास : २२२१५८, ऑफीस : २२२१५७, फॅक्स : २२३४१६.\nजा. नं. 22 2.0 Se ८००39 2 दिनांक : 2 ४ 00 180 15\nप्रति,\nमा.श्री. सुरेशजी प्रभु,\nरेलमंत्री,भारत सरकार,\nनई दिल्ली.\nविषय :- कर्नाटक एवं महाराष्ट्र राज्य के सर्वांगीण विकास के लिए कराड-\nइचलकरंजी-निपाणी-बेलगाम रेल मार्ग को मंजूरी मिल॑ हेतू...\nमाननीय महोदय,\nआप जानतेही की कराड-इचलकरंजी-निपाणी-बेलगाम इस रेलमार्गका सव्हे सेंटूल\nरेल्वे पुणे की ओरसे पूर्ण हुआ है । इस नये मार्गसे हमारे गांवकोही नही अपितु अन्य अनेक शहर,गांवको\nलाभ होगा । कर्नाटक तथा महाराष्ट्र राज्य इस नये मार्गके जुडनेसे इन राज्योंकी यातायात के लिए निश्‍चीत\nही लाभ होगा। इस मार्गसे महाराष्ट्र , कर्नाटक तथा गोवा इन राज्योंको पर्यायी नया (कम\nकि.मी.अंतरवाला) रेलमार्ग उपलब्ध होगा | इस रेल मार्ग की मांग अनेक वर्षांसे होती आई है । यह रेल\nमार्ग नॅशनल हायवे ४ को समांतर रहने से भविष्य मे लाभदायी सिध्द होगा,इतनाही नही मुंबई बेंगलोर\nकॅरीडॅर के लिये भी महत्वपूर्ण रहेगा |\nआप स्वयंम जानतेही है की देश के विकास और व्यवसाय वृध्दी के लिए रेल\nकितनी महत्वपूर्ण है । भारत सरकार का लक्ष्य देश का विकास ही है। मा.प्रधानमंत्रीजी मोदीजी हमेशा रेल\nका जिक्र करते है। देश की जनसंख्या एवं उद्योग बढे है,उतने पैमाने पर नये रेलमार्ग विकसित नही हुवे है\nयह सत्यता है। लेकीन आप की ओर से नये रेलमार्ग बनानेके लिये विशेष प्रयास किये जा रहे है।\nहमारा आपसे अनुरोध है कौ आप हमने सुझाये हुये कराड-इचलकरंजी-निपाणी-\nबेलगाम इस रेलमार्ग को रेल बजेट मे मंजूरी देंगे तथा शीप्रतासे यह मार्ग पूर्ण करनेमे सहयोग करेंगे ।\nआपकी भवदीय,\nesas\n",
    "originalFile": "evidence-1787979963089-whatsapp-image-2026-08-29-at-10.32.31-am.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787979993736",
    "title": "WhatsApp Image 2026 08 29 at 10.32.32 AM (1)",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "Date",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nTHE CORPORATION OF THE CITY OF BELAGAVI\nSTINT TOE, BER बेळगावी महानगर पालिका\n(९. ४०६ BIRT हा9030ल9चे & off : City Corporation Belagavi\n2 & Subhash Nagar, BELAGAVI - 590 016\nCe 4 > 8 : 0831-2405300 (F) 24050301\nश्री. किरण कृष्णाराव सायनाक > Resi : H.No. 765/2/B. Cross No.2,\nमहापौर Bhagya Nagar, Belagavi.\nShri. Kiran Krishnarao Sayanak Cell : 9844927299\nMayor\nB.S यानाने\nRef.No. Date: 28=10=0015\nप्रती.\nमा.श्री. सुरेश प्रभु,\nरेल मंत्री, भारत सरकार,\nनवी दिल्ली.\nविषय: कराड-इचलकरंजी-निपाणी-बेलगाम रेलमार्ग को रेल बजट मे अंतिम\nमंजूरी मिलनेके विषय मे.\nमा. महोदय,\nसादर वन्दे,\nकराड-बेलगाम इस नियोजीत रेल मार्ग का सर्व्हे दो साल पहिले पूरा हो चुका है! इसका रिपोर्ट रेल्वे\nबोर्ड को भेजा है! इस नये रेल मार्ग से अनेक नये ग्राम तथा शहर रेल मार्ग से जुडेगे! इसलिए्‌ स्थानीक\nनागरीको मे अपेक्षापूर्ती का माहोल है! इस कार्य मे आपका एवम रेल विभाग का बडा सहयोग रहा है!\nआपको हार्दिक धन्यवाद | यह विहीत करते gu अत्यंत खुशी होती है कि १७ नवे ग्राम और शहर रेल मार्ग से\nजुडेगे तथा अडोस पडोस के ५० छोटे गावोको इस रेल मार्ग का लाभ होगा! इस रेल मार्ग से ज्हर तथा\nगावोका शिप्रतासे विकास होने मे सहाय्यता मिलेगी। नये रोजगार उपलब्ध होगे!\nइस रेल मार्ग से महागष्ट्र-कर्नाटक तशा गोवा I रे माल तशा ले जाने का कार्यविस्तार होगा और\nयात्रियोको आवागमन की सुवीधा मिलेगी! भारतीय रेल की आय बढेगी कारण इचलकरंजी ज्ञहर कपडा उद्योग\nमे भारतवर्ष मे अग्रेसर जहर माना जाता है! साथ ही हुपरी चांदी उद्योग मे एक प्रमुख शहर के रुप मे प्रख्यात\nहै! तथा कागल मे अनेक नये उद्यम स्थापीत व विकसीत हो © है! कर्नाटक के निपाणी और आसपासके\nगावों मे तंबाखू बडे पैमाने पर उत्पादीत होता है! नये १७ गांव एवम शहर जुडनेके कारण आसपास के कही\nछोटेमोठे कसाबो गांवो का विकास होनेकी नई राह मिलेगी!\nकराड-इचलकरंजी-निपाणी-बेलगाम १९१ कि.मी का बताया जा रहा है! जिसमे महाराष्ट्र मे ९४.६\nकि.मी रेलमार्ग बनेगा, तथा महाराष्ट्र के इस्लामपूर-वाळवा-आष्ट-दटुधगाव-नेज-कुंभोज-इचलकरंजी-हुपरी\nतथा कागल इत्यादी गांव रेलमार्ग से जुडेगे! कर्नाटक मे ९७.३ कि.मी रेल मार्ग होगा और अडी-निपाणी-\nकणंगला-संके श्वर-हलकर्णी-दड्डी-हंदीगनुर और काकती इत्यादी गाव रेलमार्ग से जुडेगे! कराड तथा\nबेलगाम यह रेल्वे स्टेशन TERM होंगे! इस मार्ग के लिए २१०० करोड का बजेट अनुमानित है! यह नया\nरेलमार्ग मुंबई-बेगलोर-कारीडोर के लिए भी अत्यंत महत्व की भुमिका निभायेगा!\n",
    "originalFile": "evidence-1787979975048-whatsapp-image-2026-08-29-at-10.32.32-am-1-.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787980004513",
    "title": "WhatsApp Image 2026 08 29 at 10.32.32 AM (2)",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "Date",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nSTD 08338\npo वक & Office 220053\nSou. Namrata Shirish Kamate, president\n> CITY MUNICIPAL COUNCIL, NIPANI.\n818, Sakharwadi, NIPANI - 591237 (Dist. Belgaum) KARNATAKA\nMobile : 9342291401, 9342051400\nRef. No. : Date : 25|10| 2015\nप्रति,\nमा. श्री सुरेशजी प्रभु,\nTEA, भारत सरकार\nनई दिल्ली.\nविषय : समृचित विकास के लिये कराड-इचलकरंजी-निपाणी-बेलगाव रेल मार्ग को मंजूरी मिलने हेतू.\nमहोदय,\nसप्रेम नमस्कार ।\nकराड-इचलकरंजी-निपाणी-बेळगाव इस रेल मार्ग का सें कुष्ठ समय पुर्ण हुआ। इस मार्ग का नक्षा हमे प्राप्त हुआ । नकणे\nको देथनेसे पता चला की इस मार्गते महाराष्ट्र तथा कर्नाटक के अनेक नवे शहर तथा TER gH । इस मार्गपर ap गांव\nतथा शहर ऐल है जो उद्योग क्षेत्रमे तथा व्यापार मे अपनी अलग पहचान रखते है । इस रेल मार्ग से उद्योग क्षेत्र को ae पिलेगा\nक्योंकी इर शहरोंमे उत्पादित होनेवाला माल बाहर भेजने के लिये नया सस्ता पर्याय रेलके माध्यमसे उपलब्ध होगा । इसते तजीते\nविकास होगा तथा रेल्वे को भी ट्रान्सपेटेशन के माध्यमसे अधिक मुनाफा होगा ।\nआपने तैयार किया हुआ नया Yo निश्‍चितही सराहनीय है । इस मार्गसे पश्‍चिम महाराष्ट्र तथा उतर कर्नाटक के द\nइलाके तुडनेमे सहायता होगी | इस मार्गपर रेत सेवा अत्यंत आवश्यक है । दुसरा फायदा यह की इस मार्ग से बनानेसे फासला याने\nकि मी कम होंगे । डिझल की बचत होगी । कराड तथा बेळगाव ये गांव जंगशन होंगे । इस रेल मार्ग से विकास मे गती आवेगी\nऔर यही हमारे प्रथानमंतरीजी की हार्दिक इच्छा है । विकास कार्य मे रेलकी भुमिका सबपे प्रमृष है ।\nअतः हम आपसे निवेदन करते है की इस रेल मार्ग को अंतिम मंजूरी देवे तथा इस मार्ग का निर्माण जल्दसे जलद करवावे\nहमारा अनेक वर्षा का रेलका सपणा पुर्ण करनेमे सहयोग करेंगे । यही Be कामना करते है ।\nGaal\nTIER,\nसौ. नग्रता शिरीष कमते,\nनिपाणी नगरपालिका निपाणी\n",
    "originalFile": "evidence-1787979993737-whatsapp-image-2026-08-29-at-10.32.32-am-2-.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787980011568",
    "title": "WhatsApp Image 2026 08 29 at 10.32.32 AM",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nHm 4 धनंजय उर्फ सुधीर हरी गाडगीळ\n12588 Pe * आवार\nबहाल विधाता महाराष्ट्र सांगली विधानसभा मतदार संघ\nजा. क्र.७९६-” /-२७१५७ दिनांक 0g / 959 / २०१५\nप्रति,\nमा.श्री. सुरेश प्रभुजी,\nरेलमंत्री,\nभारत सरकार,\nनई दिल्ली.\nविषय - कराड-इचलकरंजी-निपाणी-बेलगाम रेल मार्ग को मंजूरी मिले ।\nकराड-इचलकरंजी-निपाणी-बेलगाम इस रेलमार्गका सर्व्हे सेंट्रल रेल्वे पुणे की ओरसे पूर्ण हुआ\nहे । इस नये मार्गसे हमारे गांवकेही नही अपितु अनेक शहर गावको लाभ होगा । इस रेल मार्ग की\nमांग अनेक वर्षांसे होती आ रही हे । यह रेल मार्ग नॅशनल हायवे ४ हो समांतर रहने से भविष्य मे\nलाभदायी सिध्द होगा |\nहमारा आपसे अनुरोध हे की आप हमने सुझाये कराड-इचलकरंजी-निपाणी-बेलगाम रेल मार्ग\nको रेल बजेट मे मंजूरी दे तथा यह मार्ग पूर्ण करनेमें सहयोग करे |\nधनंजय | हरी गाडगीळ\n( सदस्य)\nकार्यालय : कमल हाईटस्‌, तळमजला, सांगली-मिरज रोड, सांगली ४१६४१५ ० दूरध्वनी : 0२३३-२३०४४४४, ६०६७४००\n",
    "originalFile": "evidence-1787980004514-whatsapp-image-2026-08-29-at-10.32.32-am.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787980021742",
    "title": "WhatsApp Image 2026 08 29 at 10.32.33 AM (1)",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nशतकोत्तर हिरक महोत्सवी अ. नगराध्यक्षा, आश नगरपरिषद, आष्टा,\nआष्टा नगरपरिषद, wi ale\nजावके क्र. 2€19 ) 2099-98 Lr\nप्रति,\nमा. श्री. सुरेशजी प्रभु,\nरेलमंत्री, भारत सरकार,\nनई दिल्ली.\nविषय :- नये शहर तथा गांवोंको रेल सेवा उपलब्ध होने के लिये कराड-\nइचलकरंजी निपाणी बेलगाम रेल्वे मार्ग को मंजूरी मिलें.\nमहोदय,\nकराड-इचलकरंजी-निपाणी-बेलगाम इस मार्गका सर्व्हे गत दोन वर्ष पूर्ण हुआ | इस\nनियोजित रेल मार्गपर हमारा गांव भी आता है । इससे यहाँके स्थानिक निवासीयोंमे बडी प्रसन्नता\nहै। आपको एवम रेल्वे प्रशासनको हम शतशः धन्यवाद देते है। इस मार्ग के लिये अनेक वर्षांसे\nप्रयास हो रहा है।\nमहाराष्ट्र तथा कर्नाटक राज्य के अनेक नये जिले तथा तहसिल इस नये रेल मार्गसे\nSTEM | इससे यात्रीको लाभ मिलेगाही उद्योग, व्यापार एवं खेती का विकास होनेमें विशेष रुप से\nमदत होगी ।\nउपर सुझाये गये इस रेल मार्ग का सर्व्ह होनेसे हमारी बहुतसारी आशाए अंकुरीत हुयी है।\nआशा करते है की आप शीप्रही इस मार्ग को मंजूरी देकर अल्प समय मे ही इस नये रेल मार्ग का\nनिर्माण करेंगे व विकास की नयी राह प्रदान करेंगे | zt\n<< (सौ. मंगला विलासराव शिंदे)\n\\ ७ J emer नगरपरिषद, आष्टा\n\\ 2\nEZ\nAo TO 6 ~\nXT cavewater Loe. Civ outa Blood Donation Donation\n",
    "originalFile": "evidence-1787980011569-whatsapp-image-2026-08-29-at-10.32.33-am-1-.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787980033893",
    "title": "WhatsApp Image 2026 08 29 at 10.32.33 AM (2)",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\n१\namy x उल्हास संभाजी पाटील\nboa आमदार\nमहाराष्ट्र विधानसभा\nजावक क्रमांक. दिनाक र\nजँक्र.उपा/२०१६/५८८ . ११/०१/२०१६\nप्रति,\nमा. ना. सुरेश प्रभू जी,\nरेलमंत्री, भारत सरकार,\nनई दिली.\nविषय -- कराड - इचलकरंजी (महाराष्ट्र) - निपाणी - बेलगाम (कर्नाटक) नये रेलमार्ग के\nमंजुरी मिलने हेतु...\nमहोदय,\nमहाराष्ट्र , कर्नाटक इन दो राज्यों को जोडनेवाला कराड - इचलकरंजी - निपाणी - बेलगाम यह रेल\nमार्ग हो ऐसी कई सालों से मांग है। यह रेल मार्ग बने तो इससे बहुतसे गाव और शहर जुडे जा सकते है।\nइस मार्ग के बनने से इसके मार्ग में आनेवाले गाव और शहरो में परिवहन की सुविधा आसानी 'से मिल\nसकती है। इस मार्ग मे आनेवाले शहर आपने आपमें एक पहेचान है। इनमें कराड, मिरज, जयसिंगपूर,\nइचलकरंजी, कागल, निपाणी और बेलगाम जैसे औद्योगिक क्षेत्र के शहर आते है। इससे उद्योग क्षेत्र का\nलाभ हो सकता है। यह मार्ग कराड से बेलगाम जाने के लिए बहुतही किफ़ायती, फ़ायदेमंद और\nआरामदायी हो सकता है।\nइसके पुर्व रेल मंत्रीजी ने रेल बजट मे इस मार्ग को मंजुरी दी है। इसके तुरंत बाद सव्हे भी पूरा हो\nचुका है। यह नया रेल मार्ग १९१ कि.मी. का है, इसको बनाने मे लगभग २१०० करोड रूपये खर्च का\nअनुमान है। अन्य राज्यों की तुलना में महाराष्ट्र और कर्नाटक राज्य विकास की रफ़्तार निश्‍चित ही\nकाबिले तारिफ़ है। लेकीन विकास की गती के साथ इन राज्यो मे रेल सुविधा तथा नये रेल मार्ग जितनी\nपर्याप्त मात्रा मे होनी थी उतनी हुई नही। इन राज्यों के विकास मे रेल सहभाग महत्वपुर्ण है। लेकिन और\nतेजीसे उन्नती करने के लिए पर्याप्त रेल मागां की आवश्यकता है।\nआप से अनुरोध है की, महाराष्ट्र, कर्नाटक राज्यों के साथ पुरे भारत वर्ष की उन्नती TER से होने\nके लिए कराड - इचलकरंजी - निपाणी - बेलगाम इस नये रेल मार्ग को रेल बजट मे मंजुरी दे यह\nबिनती है।\nश्री. hr पाटील\nवि.स.स.\nजुना कुरूंदवाड रस्ता, भुमाता दुध संस्था, शिरोळ. ता. शिरोळ, जि. कोल्हापूर. पिन : ४१६ १०३.\nफोन व फॅक्स : (०२३२२) २३६२५१. 3\n",
    "originalFile": "evidence-1787980021743-whatsapp-image-2026-08-29-at-10.32.33-am-2-.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  },
  {
    "id": "ev-1787980045925",
    "title": "WhatsApp Image 2026 08 29 at 10.32.33 AM",
    "category": "Other Evidence",
    "date": "",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "",
    "extractedText": "--- पान 1 ---\nSHANKARAPPA S. SHIRKOLI Tel. No: 08333-273308\nPresident Mob: +91 9448036661\nदिनांक :- 0L-12.20/5\nमा. श्री.सुरेशजी प्रभु.\nरेलमंत्री, भारत सरकार, ठर\nनई दिल्ली.\nविषय :- समुचित विकास के लिये कराड-इचलकरंजी-निपाणी-बेलगाव रेल न\nमार्ग को मंजूरी मिलने हेतू.\nमहोदय.\nसप्रमे नमस्कार)\nकराड-इचलकरंजी-निपाणी-बेलगाव इस रेल मागं का सव्हे कुछ समय पुर्ण हुआ | इस मार्ग का नक्षा\nहमे प्राप्त हुआ। नकशे को देखनेसे पता चला को इस मार्गसे महाराष्ट्र तथा कर्नाटक के अनेक नये शहर तथा\nगाव रेलमार्गसे STE । इस मार्गपर कुछ गांव तथा शहर ऐसे है जो उद्योग क्षेत्रमे तथा व्यापार मे अपनी अलग\nपहचान रखते है। इस रेल मार्ग से उद्योग क्षेत्र को बढावा मिलेगा क्योंकी इन शहरोमे उत्पादित होनेवाला माल\nबाहर भेजने के लिये नया सस्ता पर्याय रेलके माध्यमसे उपलब्ध होगा | इससे तजीसे विकास होगा तथा रेल्वे\nको भौ ट्रान्सपोटॅंशन के माध्यमसे अधिक मुनाफा होगा।\nआपने तैयार किया हुआ नया रेलमार्ग निश्‍चितही सराहनीय है। इस मार्गसे पश्‍चिम महाराष्ट्र तथा उत्तर\nकर्नाटक के कई इलाके जुडनेमे सहायता होगी | इस मार्गपर रेल सेवा अत्यंत आवश्यक है। दुसरा फायदा यह\nकी इस मार्ग से बनानेसे फासला याने कि.मी. कम होंगे । डिझल की बचत होगी | कराड तथा बेलगाम ये गांव\nजंगशन होंगे। इस रेल मार्ग से विकास मे गती आयेगी और यही हमारे प्रधानमंत्रीजी की हार्दिक इच्छा है।\nविकास कार्य मे रेलकी भुमिका सबसे प्रमुख है।\nअतः हम आपसे निवेदन करते है की इस रेल मार्ग को अंतिम मंजूरी देवे तथा इस मार्ग का निर्माण\nजल्दसे जल्द करवाके हमारा अनेक वर्षांका रेलका सपना पुर्ण करनेंमे सहयोग करेंगे । यही विनम्र कामना\nकरते है।\nShankarappa 89. Shirkoli\nSs oliotal\nPresident\nShankarappa 8. Shirkoli\nPresident\nTown Municipal Council.\nSANKESHWAR\n",
    "originalFile": "evidence-1787980033894-whatsapp-image-2026-08-29-at-10.32.33-am.jpeg",
    "status": "draft",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-29T05:03:14.495Z",
    "updatedAt": "2026-08-29T05:03:14.495Z"
  }
];
