// सरकारी कागदपत्रे व पुरावे — edited via admin.html "सरकारी कागदपत्रे" tab.
// summary text is ADMIN-REVIEWED. extractedText (OCR) is used for search only.
const EVIDENCE_DOCS = [
  {
    "id": "ev-1787383568850",
    "title": "RTI 12-8-26 (C.Gov)",
    "category": "Railway / Government Letters",
    "date": "12.08.2026",
    "authority": "",
    "referenceNumber": "",
    "tags": [],
    "summary": "केंद्रीय रेल्वेच्या मुख्य प्रशासकीय अधिकाऱ्यांनी (बांधकाम) दिलेलं RTI उत्तर. यात नमूद आहे: हातकणंगले–इचलकरंजी नवीन रेल्वे मार्ग (8 किमी) 2017-18 च्या Pink Book मध्ये समाविष्ट होता. या प्रकल्पाचा Detailed Project Report (DPR) रेल्वे बोर्डाकडे 02.01.2020 रोजी सादर करण्यात आला — खर्च ₹180.73 कोटी व ROR (-12.73%). प्रकल्प अद्याप रेल्वे बोर्डाच्या तपासणीत (scrutiny) असून मंजूर झालेला नाही, त्यामुळे पुढील तपशील अद्याप शेअर करता येत नाहीत असं उत्तरात नमूद आहे.",
    "extractedText": "--- पान 1 ---\n—\nCENTRALRAILWAY\n« IND;\n$F ao Sy Office of the\n(4 ERIE Chief Administrative Officer (Const.)\nSe. 6\" floor, New Administrative Building\nSi il D.N. Road, CSMT, Mumbai-400 001\nNo. EW/106/RT1/2026/0L-295 Date: - 12.08.2026\nShri Vicky Manisha Balu Lokare\nSub: Information required under Section 6(1) of the RTI Act 2005.\nRef: Online RTI application No. CRAIL/R/T/26/00731 dated 22.07.2026.\nhocks\nर With reference to the above, the information available in Central Railway Construction\nOrganization for Hatkanangale -Ichalkaranji Railway project is given as under: -\nInformation Sought\n\n1 Please provide the certified copies of the | The work of Hatkanangale -\nofficial file notings and processing history of | Ichalkaranji new Railway line (8Km)\nthe Detailed Project Report (DPR) for the | appeared in the Pink Book of 2017-18.\nHatkanangale-Ichalkaranji New BG line which | The Detailed Project Report (DPR) of\nwas submitted to the Railway Board by the | the said project was submitted to the\nCentral Railway Construction Wing in the year | Railway Board on 02.01.2020, ata cost\n2018. प of Rs. 180.73 crore & ROR (-12.73%).\n\nThe same is under scrutiny of Railway\nBoard.\n\nProject is not sanctioned yet, hence\ndetails cannot be shared.\n\n2 As per the official Twitter announcement by | Under the RTI Act, public authorities\nCentral Railway dated 11 June 2017 the | are not obligated to answer questions\nfoundation stone for the Final Location Survey | that seek explanations, reasons,\nof this line was laid by the then Minister of | opinions, or justifications for actions\nRailways. Please state the specific technical or | or decisions. The Act focuses on\nfinancial reasons why the Railway Board has | providing access to information in the\nnot granted final sanction to this project even | form of records, documents, etc,\nafter 8 years. rather than interpretations or\n\nopinions.\nPlease provide copies of any correspondence | Project is not sanctioned yet, hence\nor official remarks exchanged between the | details cannot be shared.\nRailway Board and NITI Aayog or the Ministry\nof Finance regarding the fund allocation. for\nthis specific Hatkanangale-Ichalkaranji rail\nlink.\n\n4 Please intimate whether this project is | The work of Hatkanangale-\ncurrently under consideration for inclusion in | Ichalkaranji new Railway line (8Km)\nthe upcoming Pink Book or Budgetary | appeared in the Pink Book 0f2017-18.\nAllocation. What is the current official status of | The Detailed Project Report (DPR) of\nthis project file in the Railway Board? the said project was submitted to the\n\nRailway Board on 02.01.2020, ata cost\nof Rs. 180.73 crore & ROR (-12.73%).\nThe same is under scrutiny of Railway\nBoard.\n(scanned with OKEN Scanner\n\n--- पान 2 ---\nPeriod to which information relates: June 2017 | The work of ) Hatkanangale-\nto May 2026. Ichalkaranji new Railway line (8Km)\nappeared in the Pink Book of 2017-18.\nThe Detailed Project Report (DPR) of\nthe said project was submitted to the\nRailway Board on 02.01.2020, ata cost\nof Rs. 180.73 crore & ROR (-12.73%).\nThe same is under scrutiny of Railway\nBoard.\nFormat of Information: Certified Copies via | Project is not sanctioned yet, hence\nRegistered Post or Online RTI Portal. | details cannot be shared.\nThis is for your information please.\nIf you are not satisfied with this information, appeal to the above lies with the 1st Appellate\nAuthority, within 30 days, from the date of receipt of this communication.\nThe name and address of the First appellate Authority are given Below: -\nChief Engineer (Construction) South,\nFirst Appellate Authority,\nCAO (C)’s Office, NAB Bldg.,\n6th Floor, D.N. Road,\nCST Mumbai-400 001.\n3 5\noii\nDy.\\CE(C)PLG & CPIO\nRly. No. - 022674-54310\nEmail- dycecpl@gmail.com\n(scanned with OKEN Scanner",
    "originalFile": "evidence-1787383566049-rti-12-8-26-c.gov-.pdf",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "createdAt": "2026-08-22T07:26:08.850Z",
    "updatedAt": "2026-08-22T07:26:08.850Z"
  },
  {
    "id": "ev-1956-loksabha",
    "title": "लोकसभा प्रश्न क्र. 1205 — Ichal-Karanji ते Kolhapur-Miraj रेल्वे जोडणी (19 डिसेंबर 1956)",
    "category": "Railway / Government Letters",
    "date": "19.12.1956",
    "authority": "लोकसभा (Lok Sabha), भारत सरकार",
    "referenceNumber": "प्रश्न क्र. 1205, Written Answers पान 1799-1800",
    "tags": [
      "1956",
      "Lok Sabha",
      "Parliament",
      "Historical",
      "Earliest Record"
    ],
    "summary": "खासदार श्री. कजरोळकर यांनी लोकसभेत विचारलेला प्रश्न क्र. 1205 (19 डिसेंबर 1956, Written Answers, पान 1799-1800), शीर्षक: \"Railway Connection from Ichal-Karanji to Kolhapur-Miraj Line\". प्रश्न: महाराष्ट्र चेंबर ऑफ कॉमर्स, पुणे यांच्याकडून सरकारला असं निवेदन मिळालं आहे का, की कोल्हापूर-मिरज दरम्यान टाकल्या जाणाऱ्या ब्रॉडगेज मार्गाला हातकणंगल्याऐवजी इचलकरंजीशी जोडावं (इचलकरंजीच्या औद्योगिक व व्यावसायिक महत्त्वामुळे)? रेल्वे व वाहतूक उपमंत्री (श्री. अळगेसन) यांचं उत्तर: (अ) होय, असं निवेदन मिळालं आहे. (ब) कोल्हापूर-मिरज मीटरगेज मार्गाच्या ब्रॉडगेजमध्ये रूपांतरणासाठी प्राथमिक अभियांत्रिकी व वाहतूक सर्वेक्षणाचा अंदाज मध्य रेल्वेकडून मागवण्यात आला असून, हातकणंगल्याऐवजी इचलकरंजीला जोडण्याचा मुद्दा त्या सर्वेक्षणादरम्यान विचारात घेतला जाईल असं नमूद केलं आहे.",
    "extractedText": "Railway Connection from Ichal-Karanji to Kolhapur-Miraj Line. 1205. Shri Kajrolkar: Will the Minister of Railways be pleased to state: (a) whether a representation has been received by Government from the Maharashtra Chamber of Commerce, Poona, requesting to connect Ichal-Karanji instead of Hathkanangale to the broad-gauge line to be laid between Kolhapur and Miraj on account of the industrial and commercial importance of Ichal-Karanji; and (b) if the reply to part (a) be in the affirmative, what steps Government propose to take in the matter? The Deputy Minister of Railways and Transport (Shri Alagesan): (a) Yes. (b) An estimate for Preliminary Engineering and Traffic Surveys for conversion of Kolhapur Miraj M.G. section into B.G. has been called for from the Central Railway. The question of connecting Ichal-Karanji instead of Hathkanangale has been noted for consideration during the survey.",
    "status": "published",
    "version": 2,
    "previousVersions": [],
    "originalFile": "evidence-1956-lok-sabha-reference.pdf",
    "createdAt": "2026-08-22T13:07:48.131Z",
    "updatedAt": "2026-08-26T01:32:12.835Z"
  },
  {
    "id": "ev-1929-story-of-ichalkaranji",
    "title": "The Story of Ichalkaranji (1929) — H. George Franks — रेल्वे मार्गाचा सर्वात जुना ज्ञात उल्लेख",
    "category": "Other Evidence",
    "date": "1929",
    "authority": "H. George Franks (लेखक) — Scottish Mission Industries, Poona (प्रकाशक)",
    "referenceNumber": "Chapter VIII, पान 133–134",
    "tags": [
      "1929",
      "History",
      "Book",
      "Miraj-Kolhapur Railway",
      "Earliest Reference",
      "Narayanrao Babasaheb"
    ],
    "summary": "या पुस्तकाच्या आठव्या प्रकरणात (पान 133 च्या शेवटी सुरू होऊन 134 वर पूर्ण होणाऱ्या वाक्यात) असं नमूद आहे की इचलकरंजीच्या राजधानीला मिरज-कोल्हापूर रेल्वेशी एका शाखा मार्गाने जोडण्यासाठी काही काळापासून जोमदार प्रयत्न सुरू होते, जेणेकरून या समृद्ध खोऱ्यातील व्यावसायिक मालाची सुलभ ने-आण करता येईल. मूळ इंग्रजी वाक्य: \"for some time vigorous efforts have been made to connect the capital of Ichalkaranji with a branch line to the Miraj-Kolhapur Railway, which would open facilities for easy transhipment of commercial goods from the rich valley in which the capital town is situated.\" — सध्या उपलब्ध पुराव्यांमधील हा रेल्वे जोडणीच्या मागणीचा सर्वात जुना ज्ञात संदर्भ आहे (1956 च्या संसदीय प्रश्नापेक्षाही जुना).",
    "extractedText": "",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "originalFile": "evidence-1929-story-of-ichalkaranji.pdf",
    "createdAt": "2026-08-25T10:06:09.593Z",
    "updatedAt": "2026-08-25T10:06:09.607Z"
  },
  {
    "id": "ev-2015-karad-belgaum-proposal",
    "title": "कराड–इचलकरंजी–निपाणी–बेळगाव प्रस्तावित नवीन रेल्वे मार्ग — सर्वेक्षण तपशील व लोकप्रतिनिधी/नागरी संस्था पाठिंबा पत्रे (2015-16)",
    "category": "Railway / Government Letters",
    "date": "2015-2016",
    "authority": "विविध — इचलकरंजी रेल्वे कृती समिती, आमदार (महाराष्ट्र व कर्नाटक), विविध नगरपरिषदा/महानगरपालिका",
    "referenceNumber": "बहुविध पत्रे — तपशील सारांशात",
    "tags": [
      "Karad-Belgaum",
      "191.9 किमी",
      "Nipani",
      "Islampur",
      "Sankeshwar",
      "2015",
      "Support Letters",
      "Alternate Proposal"
    ],
    "summary": "⚠️ महत्त्वाची सूचना: हा प्रस्ताव सध्याच्या History/Project Status पानांवरील हातकणंगले–इचलकरंजी 8 किमी शाखा मार्गाच्या DPR (2017/2020) पेक्षा पूर्णपणे वेगळा आहे — गोंधळ टाळण्यासाठी वेगळा ठेवला आहे.\n\nहा एक मोठा, स्वतंत्र प्रस्तावित नवीन रेल्वे मार्ग आहे: कराड–इचलकरंजी–निपाणी–बेळगाव (एकूण 191.9 किमी — महाराष्ट्रात 94.6 किमी, कर्नाटकात 97.3 किमी). सर्वेक्षण तपशील: Take-off Point — Shenoli Yard (पुणे-मिरज मार्गावर); Meeting Point — Sambre Station (मिरज-बेळगाव मार्गावर); एकूण 21 स्थानके (4 अस्तित्वात: कराड, शेणोली, सांबरे, बेळगाव; 17 प्रस्तावित: तांबवे, इस्लामपूर, वाळवा, आष्टा, दुधगाव, नेज, इचलकरंजी, हुपरी, कागल, आडी, निपाणी, कणगला, संकेश्वर, हलकर्णी, दड्डी, हंडिगणूर, काकती); निपाणी-कणगला दरम्यान 2.85 किमी लांबीचा 1 बोगदा; गेज 1676mm सिंगल लाईन; गती 60-110 किमी/तास.\n\n2015-16 मध्ये अनेक लोकप्रतिनिधी व स्थानिक स्वराज्य संस्थांनी रेल्वे मंत्री सुरेश प्रभू व पंतप्रधान नरेंद्र मोदी यांना हा मार्ग मंजूर करण्याची विनंती करणारी पत्रे पाठवली — इचलकरंजी रेल्वे कृती समिती, आमदार सुरेश हाळवणकर (इचलकरंजी), आमदार शिवेंद्रसिंहराजे भोसले (सातारा), आमदार शशिकला जोल्ले (निपाणी, कर्नाटक), इस्लामपूर नगरपरिषद, आष्टा नगरपरिषद, निपाणी नगरपालिका (कर्नाटक), संकेश्वर नगरपरिषद (कर्नाटक), बेळगावी महानगरपालिका, कराड नगरपरिषद. पत्रांमध्ये नमूद अंदाजित खर्च ₹2100 कोटी (एका पत्रानुसार — हा आकडा DPR सारखा अधिकृत दस्तऐवज नाही, त्यामुळे पडताळणी आवश्यक).",
    "extractedText": "Karad Belgaum Railway Proposal. Salient features of the proposed new line: Route - Karad Belgaum via Nipani. Gauge - 1676mm (Single Line). Ruling Gradient - 1:150 in Plain terrain, 1:80 in Ghat Section for length of 1.5 Kms. Length in Kms - 191.9km (94.6 km in Maharashtra and 97.3 km in Karnataka). Speed - 60kmph for Ghat section and 110kmph for sectional length other than Ghat section. Take off Point - Shenoli Yard on Pune-Miraj section of CR. Meeting Point - At Sambre Station on MRJ end MRJ-Belgaum Section of SWR Rly. Nos of stations - 21 Nos. Existing Stations - Karad, Shenoli, Sambre, Belgaum. Proposed Stations - Tambhave, Islampur, Walva, Ashta, Dudhgaon, Nej, Ichalkaranji, Hupari, Kagal, Adi, Nipani, Kanagala, Sankeshwar, Halkarni, Daddi, Handignur, Kakati. Tunnels - 1 Nos of length 2.85 kms near Nipani from km 117.45 to 120.30 between proposed Nipani and Kanangala station. Support letters to Railway Minister Suresh Prabhu and PM Narendra Modi from Ichalkaranji Railway Kruti Samiti, MLA Suresh Halwankar, MLA Shivendrasinghraje Bhosale, MLA Shashikala Jolle Nipani, Islampur Nagarparishad, Aashta Nagarparishad, Nipani City Municipal Council, Sankeshwar Town Municipal Council, Corporation of the City of Belagavi, Karad Nagarparishad, dated between October 2015 and December 2015.",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "originalFile": "evidence-2015-karad-belgaum-railway-proposal.pdf",
    "createdAt": "2026-08-27T03:52:09.921Z",
    "updatedAt": "2026-08-27T03:52:09.935Z"
  },
  {
    "id": "ev-2026-mp-mane-letter",
    "title": "खासदार धैर्यशील माने यांचे रेल्वे मंत्र्यांना पत्र — हातकणंगले-इचलकरंजी मार्ग शीघ्र पूर्ण करण्याची विनंती (22 जुलै 2026)",
    "category": "Railway / Government Letters",
    "date": "22.07.2026",
    "authority": "श्री. धैर्यशील संभाजीराव माने, खासदार (लोकसभा) — मा. श्री. अश्विनी वैष्णव, रेल्वे मंत्री, भारत सरकार यांना",
    "referenceNumber": "जा.क्र. डीएसएम/३८/२०२६ — रेल्वे बोर्ड प्राप्ती शिक्का: 04 AUG 2026",
    "tags": [
      "2026",
      "MP Letter",
      "Dhairyasheel Mane",
      "Ashwini Vaishnav",
      "Karad-Belgaum",
      "Pink Book",
      "GST",
      "Budget"
    ],
    "summary": "खासदार धैर्यशील संभाजीराव माने यांनी रेल्वे मंत्री अश्विनी वैष्णव यांना लिहिलेलं अधिकृत पत्र — हातकणंगले-इचलकरंजी 8 किमी रेल्वे मार्ग शीघ्रतेने पूर्ण करण्यासाठी सहकार्याची विनंती. यातील महत्त्वाचे मुद्दे:\n\n🔗 अत्यंत महत्त्वाची स्पष्टता: \"हातकणंगले–इचलकरंजी रेलमार्ग जो मात्र ८ कि.मी. का है, यह रेलमार्ग कराड-बेलगाम (१९१ किमी) रेलमार्गका हिस्सा है\" — म्हणजे हा 8 किमी मार्ग स्वतंत्र नसून कराड-इचलकरंजी-निपाणी-बेळगाव या मोठ्या 191 किमी प्रकल्पाचाच भाग आहे. 2011 मध्ये कराड-बेळगाव मार्गाच्या सर्वेक्षणाला मंजुरी मिळाली, आणि 2013 मध्ये मध्य रेल्वे, पुणेने सर्वेक्षण पूर्ण करून अहवाल रेल्वे बोर्डाकडे पाठवला. भविष्यात कराड-बेळगाम मार्गाला मंजुरी मिळाली तर हातकणंगले-इचलकरंजी मार्ग आपोआप त्याला जोडला जाईल असं नमूद.\n\n📅 अर्थसंकल्पीय इतिहास: 2017 च्या अर्थसंकल्पात ₹150 कोटींची तरतूद व 2017-18 मध्ये ₹10 कोटी वितरित; भूमिपूजन 11.06.2017 रोजी तत्कालीन रेल्वेमंत्री सुरेश प्रभू यांच्या हस्ते; 2019-20 मध्ये टोकन ₹10,000 तरतूद व ₹10 लाख वितरित; 5 जुलै 2019 रोजी रेल्वे विभागाच्या Pink Book मध्ये समावेश; ⚠️ या पत्रात असंही नमूद आहे की या मार्गाचं सर्वेक्षण मध्य रेल्वे, पुणेने ऑगस्ट 2018 मध्ये पूर्ण करून DPR रेलभवनला पाठवला — ही तारीख साईटवर आधीच नोंदवलेल्या 30.11.2017 (मूळ DPR) व 02.01.2020 (सुधारित DPR) या तारखांशी पूर्णपणे जुळत नाही, त्यामुळे ही एक Conflicting Record आहे — पुढील पडताळणी आवश्यक.\n\n😞 अलीकडची निराशा: 2020-22 च्या अर्थसंकल्पात केवळ ₹1,000 (नाममात्र टोकन) वितरित करण्यात आले, अपेक्षित मुख्य निधी मिळाला नाही.\n\n💰 आर्थिक महत्त्व: पत्रानुसार इचलकरंजीतील कापड उद्योग, स्पिनिंग मिल, सिमेंट, कच्चा माल, पॅकिंग मटेरियल, कोळसा इत्यादींमधून दरवर्षी अंदाजे ₹5,200 कोटी GST भरला जातो.",
    "extractedText": "Dhairyasheel S. Mane, Member of Parliament - Loksabha. Member: Standing Committee on Home Affairs, Consultative Committee on Ministry of Textiles. Ja.Kr. DSM/38/2026, Dt. 22.07.2026. To: Shri Ashwini Vaishnav, Railway Minister, Government of India, New Delhi. Subject: Hatkanangale-Ichalkaranji 8 km railway line - regarding necessary cooperation for speedy completion. Received by Ministry of Railways (Railway Board) 04 AUG 2026. Content: 2017 budget provision of Rs.150 crore for approval, Rs.10 crore allocated 2017-18. 2019-20 token provision Rs.10,000, Rs.10 lakh allotted. Included in Pink Book 5 July 2019. Foundation stone laid by then Railway Minister Suresh Prabhu on 11-06-2017. Hatkanangale-Ichalkaranji railway line is part of Karad-Belgaum (191 km) railway line. In 2011 survey of Karad-Belgaum line was approved, in 2013 Central Railway Pune completed survey and sent report to Railway Board. If Karad-Belgaum line gets approval in future, Hatkanangale-Ichalkaranji will automatically be connected. Survey of this line completed by Central Railway Pune in August 2018, DPR report sent to Rail Bhavan. In 2020-22 budget only token Rs.1000 was allotted, causing disappointment. Ichalkaranji textile industry pays approximately Rs.5200 crore GST annually from textile, spinning mills, cement, raw materials, packing material, coal etc.",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "originalFile": "evidence-2026-mp-mane-letter.pdf",
    "createdAt": "2026-08-27T03:59:18.708Z",
    "updatedAt": "2026-08-27T03:59:18.725Z"
  },
  {
    "id": "ev-1965-tarun-bharat",
    "title": "तरुण भारत वृत्त — इचलकरंजी रेल्वेसाठी पालिकेचा 1965 चा ठराव",
    "category": "Photos / Scanned Documents",
    "date": "1965 (नेमकी मासिक तारीख अस्पष्ट — पत्रिकेवर फक्त \"20 नोव्हेंबर\" दिसतं, वर्षाचा अंक अस्पष्ट)",
    "authority": "तरुण भारत (वृत्तपत्र)",
    "referenceNumber": "",
    "tags": [
      "1965",
      "Municipal Resolution",
      "Tarun Bharat",
      "Newspaper",
      "Miraj-Kolhapur Broad Gauge"
    ],
    "summary": "तरुण भारत वृत्तपत्रातील बातमी — मथळा: \"इचलकरंजीत रेल्वे येण्यासाठी पालिकेचा 1965 ला ठराव\". उपमथळा: \"मिरज-कोल्हापूर रेल्वेलाईन ब्रॉडगेज करताना इचलकरंजी रेल्वे स्टेशन : रेल्वे खात्याकडून मिळाले होते आश्वासन\". बातमीत इचलकरंजी नगरपालिकेने 1965 साली रेल्वे जोडणीसंदर्भात ठराव पारित केल्याचा आणि मिरज-कोल्हापूर मार्गाच्या ब्रॉडगेज रूपांतरणावेळी इचलकरंजी स्टेशनबाबत रेल्वे खात्याकडून आश्वासन मिळाल्याचा उल्लेख आहे. सोबत तत्कालीन नगरपालिका पदाधिकाऱ्यांचा फोटो व यादीही आहे (5 जुलै 1961 रोजी निवडून आलेले सदस्य असं नमूद). ⚠️ प्रामाणिक मर्यादा: वृत्तपत्र कात्रणाच्या फोटोतील सर्व बारीक मजकूर (उदा. नेमका ठराव क्रमांक, पूर्ण तारीख) स्पष्टपणे वाचता आलेला नाही — मथळा व मुख्य आशय स्पष्ट आहे.",
    "extractedText": "Tarun Bharat newspaper clipping. Headline: Ichalkaranjit railway yenyasathi palikecha 1965 la tharav (Ichalkaranji Municipal Council 1965 resolution for railway to come to Ichalkaranji). Subheadline: Miraj-Kolhapur railway line broad gauge karताना Ichalkaranji railway station - railway khatyakadun milale hote ashwasan (While converting Miraj-Kolhapur line to broad gauge, assurance was received from railway department regarding Ichalkaranji station). Includes photo and list of municipal council members elected 5 July 1961.",
    "status": "published",
    "version": 1,
    "previousVersions": [],
    "originalFile": "ichalkaranji-railway-historical-1965-resolution.jpg.jpg",
    "createdAt": "2026-08-27T09:31:59.877Z",
    "updatedAt": "2026-08-27T09:31:59.889Z"
  }
];
