// Master Timeline — इतिहास पानासाठी संरचित डेटा.
// प्रत्येक नोंदीला source + verification स्थिती आहे. नवीन नोंद जोडताना
// कुठलीही तारीख/आकडा बनवू नका — फक्त प्रत्यक्ष कागदपत्रावर आधारित नोंद करा.
//
// verification: "verified" (🟢 पुराव्यासह पडताळलेलं) |
//               "pending"  (🟡 पडताळणी आवश्यक) |
//               "context"  (⚪ ऐतिहासिक संदर्भ, स्वतंत्र दस्तऐवजी पुरावा नाही)
const TIMELINE_EVENTS = [
  {
    id: "t-1929",
    date: "1929-01-01",
    dateLabel: "1929",
    title: "सर्वात जुना ज्ञात प्रकाशित संदर्भ — 'The Story of Ichalkaranji'",
    description: "H. George Franks यांच्या 'The Story of Ichalkaranji' (1929, Scottish Mission Industries, Poona) या पुस्तकाच्या आठव्या प्रकरणात (पान 133 च्या शेवटी सुरू होऊन 134 वर पूर्ण होणाऱ्या वाक्यात) नमूद आहे: इचलकरंजीच्या राजधानीला मिरज–कोल्हापूर रेल्वेशी एका शाखा मार्गाने जोडण्यासाठी काही काळापासून जोमदार प्रयत्न सुरू होते, जेणेकरून या समृद्ध खोऱ्यातील व्यावसायिक मालाची सुलभ ने-आण करता येईल. सध्या उपलब्ध पुराव्यांमधील रेल्वे जोडणीच्या मागणीचा हा सर्वात जुना ज्ञात संदर्भ आहे — 1956 च्या संसदीय प्रश्नापेक्षाही 27 वर्षं जुना.",
    sourceType: "Historical Record",
    verification: "verified",
    verificationNote: "मूळ पुस्तकाची प्रत Evidence Centre मध्ये जतन केली असून, पान 133-134 वरचा नेमका मजकूर प्रत्यक्ष वाचून पडताळला आहे.",
    evidenceUrl: "evidence-detail.html?id=ev-1929-story-of-ichalkaranji",
  },
  {
    id: "t-1956",
    date: "1956-12-19",
    dateLabel: "19 डिसेंबर 1956",
    title: "लोकसभा प्रश्न — Ichal-Karanji ते Kolhapur-Miraj रेल्वे जोडणी",
    description: "खासदार श्री. कजरोळकर यांनी लोकसभेत प्रश्न क्र. 1205 विचारला (Written Answers, पान 1799-1800): महाराष्ट्र चेंबर ऑफ कॉमर्स, पुण्याकडून हातकणंगल्याऐवजी इचलकरंजीला कोल्हापूर-मिरज ब्रॉडगेज मार्गाशी जोडण्याचं निवेदन मिळालं आहे का? रेल्वे उपमंत्र्यांचं (श्री. अळगेसन) उत्तर: होय, निवेदन मिळालं असून, कोल्हापूर-मिरज मीटरगेज मार्गाच्या ब्रॉडगेज रूपांतरणाच्या सर्वेक्षणादरम्यान इचलकरंजी जोडणीचा मुद्दा विचारात घेतला जाईल.",
    sourceType: "Parliamentary",
    verification: "verified",
    verificationNote: "मूळ दस्तऐवज Evidence Centre मध्ये उपलब्ध — संपूर्ण प्रश्नोत्तर प्रत्यक्ष वाचून पडताळलं आहे.",
    evidenceUrl: "evidence-detail.html?id=ev-1956-loksabha",
  },
  {
    id: "t-1965",
    date: "1965-01-01",
    dateLabel: "1965",
    title: "इचलकरंजी नगरपालिका ठराव",
    description: "इचलकरंजी नगरपालिकेने हातकणंगले–इचलकरंजी रेल्वे मार्गाच्या मागणीसंदर्भात ठराव पारित केला — नागरिकांच्या संघटित मागणीची ही सर्वात जुनी स्थानिक प्रशासकीय नोंद आहे.",
    sourceType: "Government",
    verification: "pending",
    verificationNote: "ठरावाचा फोटो/स्कॅन गॅलरीत उपलब्ध आहे — मूळ नगरपालिका दस्तऐवज (ठराव क्रमांकासह) अद्याप Evidence Centre मध्ये औपचारिकरित्या नोंदवलेला नाही.",
    evidenceUrl: "gallery-data.js#1965",
  },
  {
    id: "t-2017-survey",
    date: "2017-06-11",
    dateLabel: "11 जून 2017",
    title: "Final Location Survey — भूमिपूजन",
    description: "मध्य रेल्वेच्या अधिकृत घोषणेनुसार, त्यावेळच्या रेल्वे मंत्र्यांच्या हस्ते या मार्गाच्या Final Location Survey साठी भूमिपूजन करण्यात आलं.",
    sourceType: "RTI",
    verification: "verified",
    verificationNote: "12.08.2026 च्या RTI उत्तरात मध्य रेल्वेने ही तारीख स्वतः नमूद केली आहे.",
    evidenceUrl: "evidence-detail.html?id=ev-1787383568850",
  },
  {
    id: "t-2017-dpr",
    date: "2017-11-30",
    dateLabel: "30 नोव्हेंबर 2017",
    title: "मूळ DPR सादर",
    description: "हातकणंगले–इचलकरंजी नवीन रेल्वे मार्गाचा (8 किमी) Detailed Project Report (DPR) रेल्वे बोर्डाकडे सादर. अंदाजित खर्च ₹191.59 कोटी, Rate of Return (ROR) −10.11%.",
    sourceType: "Official",
    verification: "verified",
    verificationNote: "प्रकल्पाच्या अधिकृत नोंदींमध्ये व साईटच्या content.js मध्ये पूर्वीपासून नमूद.",
    evidenceUrl: null,
  },
  {
    id: "t-2020-revised-dpr",
    date: "2020-01-02",
    dateLabel: "02 जानेवारी 2020",
    title: "सुधारित DPR सादर",
    description: "सुधारित Detailed Project Report रेल्वे बोर्डाकडे सादर — खर्च ₹180.73 कोटी, ROR −12.73%. हा प्रकल्प रेल्वे बोर्डाच्या तपासणीखाली (scrutiny) असल्याचं नमूद.",
    sourceType: "RTI",
    verification: "verified",
    verificationNote: "12.08.2026 च्या RTI उत्तरात मध्य रेल्वेने हीच आकडेवारी स्वतः पुन्हा पुष्टी केली आहे — दोन स्वतंत्र स्रोतांतून (content.js + RTI PDF) एकच आकडेवारी जुळते.",
    evidenceUrl: "evidence-detail.html?id=ev-1787383568850",
  },
  {
    id: "t-2026-rti",
    date: "2026-08-12",
    dateLabel: "12 ऑगस्ट 2026",
    title: "RTI उत्तर — प्रकल्प स्थिती पुष्टी",
    description: "मध्य रेल्वेच्या मुख्य प्रशासकीय अधिकाऱ्यांनी (बांधकाम) दिलेल्या RTI उत्तरात नमूद: प्रकल्प अद्याप रेल्वे बोर्डाच्या तपासणीत असून मंजूर झालेला नाही, त्यामुळे पुढील आर्थिक/निधीसंबंधित तपशील अद्याप शेअर करता येत नाहीत.",
    sourceType: "RTI",
    verification: "verified",
    verificationNote: "मूळ स्वाक्षरीयुक्त RTI उत्तर PDF स्वरूपात Evidence Centre मध्ये उपलब्ध.",
    evidenceUrl: "evidence-detail.html?id=ev-1787383568850",
  },
];
